src/objects/Attendance__c.object
<CustomObject>
    <fields>
        <fullName>Enrolment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Enrolment</label>
        <referenceTo>Enrolment__c</referenceTo>
        <relationshipLabel>Attendances</relationshipLabel>
        <relationshipName>Attendances</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Session__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The program session the client attends</inlineHelpText>
        <label>Program Session</label>
        <referenceTo>Program_Session__c</referenceTo>
        <relationshipLabel>Attendances</relationshipLabel>
        <relationshipName>Attendances</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Young_Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The person who attended the event</inlineHelpText>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Attendances</relationshipLabel>
        <relationshipName>Attendances</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Attendance</label>
    <nameField>
        <label>Attendance Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendances</pluralLabel>
    <recordTypes>
        <fullName>Course_Attendance</fullName>
        <active>true</active>
        <description>Used for program courses</description>
        <label>Course Attendance</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Enrolment__c.object
<CustomObject>
    <fields>
        <fullName>Program_Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program/Service</label>
        <referenceTo>Program_Service__c</referenceTo>
        <relationshipLabel>Enrolments</relationshipLabel>
        <relationshipName>Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status_on_Programme__c</fullName>
        <label>Status on Programme</label>
        <picklist>
            <picklistValues>
                <fullName>Waiting List</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drop-out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrew</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Young_Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Attendee</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Enrolments</relationshipLabel>
        <relationshipName>Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Enrolment</label>
    <nameField>
        <label>Enrolment Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrolments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program_Service__c.object
<CustomObject>
    <label>Program/Course</label>
    <nameField>
        <label>Program/Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs/Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program_Session__c.object
<CustomObject>
    <fields>
        <fullName>Program_Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program/Service</label>
        <referenceTo>Program_Service__c</referenceTo>
        <relationshipLabel>Program Sessions</relationshipLabel>
        <relationshipName>Program_Sessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program Session</label>
    <nameField>
        <displayFormat>Session-{DD}/{MM}/{YY}-{00}</displayFormat>
        <label>Program Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProgramSessionTrigger.cls
/*
	Author: Eamon Kelly, Enclude
	Purpose: When a new program session is created, find everyone who is enrolled in the course and create attendances for them in the session
	Tested in testCreateAttendanceTrigger 
*/
public with sharing class ProgramSessionTrigger implements TriggerDispatcher.ITriggerEntry
{
	public void MainEntry (String TriggerObject, Boolean isBefore, Boolean isDelete, Boolean isAfter, Boolean isInsert, Boolean isUpdate, Boolean isExecuting,
		list<SObject> newList, Map<Id, SObject> newMap, List<SObject> oldList, Map<Id, SObject> oldMap)
	{
		if (isInsert && isAfter)
		{
			CreateAttendancesOnNewSession (newList);
		}
	}
	
	public void CreateAttendancesOnNewSession (list<Program_Session__c> newSessions)
	{
		list<Attendance__c> attendances = new list<Attendance__c>();
		Id courseAttendanceRecordTypeId = [select Id from RecordType where sObjectType='Attendance__c' and DeveloperName = 'Course_Attendance'].Id;
    
		set <Id> servicesSet = new set <Id>();
    	for (Program_Session__c sNew: newSessions)
	    {
    		servicesSet.add (sNew.Program_Service__c);
    	}
    	map <Id, Program_Service__c> servicesMap = new map <Id, Program_Service__c>([select Id, (select Id, Young_Person__c from Participants__r where Status_on_Programme__c = 'Active') from Program_Service__c where Id in :servicesSet]);
		if (newSessions.size() < 50) // not required for mass import
		{
		    for (Program_Session__c sNew: newSessions)
		    {
		        for (Enrolment__c onePersonEnrolment: servicesMap.get(sNew.Program_Service__c).Participants__r)
	    	    {
	        	    Attendance__c oneAttended = new Attendance__c (Name='FromSession', Young_Person__c=onePersonEnrolment.Young_Person__c, Program_Session__c=sNew.id, Enrolment__c=onePersonEnrolment.id, RecordTypeId = courseAttendanceRecordTypeId);
	            	attendances.add (oneAttended);
		        } 
		    }
	    	insert attendances;
		}
	}
}