src/objects/Attendance__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <formula>CASE( RecordType.DeveloperName , &quot;Course_Attendance&quot;,  Course__c  , &quot;Drop_In_Attendance&quot;,  text(Reason_for_Attending__c)  , &quot;One_to_One_Attendance&quot;, text(Reason_for_Attending__c), &quot;Open_Access_Attendance&quot;, &quot;&quot;, null )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Description</label>
        <type>Text</type>
    </fields>
    <label>Attendance</label>
    <nameField>
        <label>Attendance Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Care_Plan_Objective__c.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <picklist>
            <picklistValues>
                <fullName>Drug &amp; Alcohol Use</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physical &amp; Psychological Problems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Problems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Functioning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Risk Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Care Plan Administration</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Care Plan Objectives</relationshipLabel>
        <relationshipName>Care_Plan_Objectives1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Care Plan Objective</label>
    <nameField>
        <label>Care Plan Objective</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Care Plan Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Care_plan_step__c.object
<CustomObject>
    <fields>
        <fullName>Care_Plan_Objective__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Care Plan Objective</label>
        <referenceTo>Care_Plan_Objective__c</referenceTo>
        <relationshipLabel>Care plan steps</relationshipLabel>
        <relationshipName>Care_plan_steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <description>Reference to the object (attendance or event) that this step refers to - set by trigger</description>
        <label>Reference</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Step_records_attendance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Step records attendance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>What_step_needs_to_happen_first__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What care plan step needs to happen first?</inlineHelpText>
        <label>What step needs to happen first</label>
        <referenceTo>Care_plan_step__c</referenceTo>
        <relationshipLabel>Care plan steps</relationshipLabel>
        <relationshipName>Care_plan_steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Care plan step</label>
    <nameField>
        <displayFormat>CPS-{00000}</displayFormat>
        <label>Care plan step name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care plan steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CustomCarePlanStepLookupController.cls
// Taken from http://blog.jeffdouglas.com/2011/08/12/roll-your-own-salesforce-lookup-popup-window/
/*
	Author: Eamon Kelly, Enclude
	Purpose: Display a list of care plan steps and that are associated with this client so that one can be selected
	Called from: Override of the lookup Button on care plan review page
	Tested in: TestCarePlanReview
*/
global with sharing class CustomCarePlanStepLookupController 
{ 
	global List<Care_plan_step__c> results{get;set;} // search results
	global string searchString{get;set;} // search keyword
	private String clientID;
	private String attendancePrefix;
  
	global CustomCarePlanStepLookupController() 
	{
		attendancePrefix = Attendance__c.sObjectType.getDescribe().getKeyPrefix() + '%';

	  	// get the current search string and the client ID from the URL
  		searchString = System.currentPageReference().getParameters().get('lksrch');
  		clientID = System.currentPageReference().getParameters().get('clientID');
  		runSearch();  
	}
   
	// performs the keyword search
	global PageReference search() 
	{
	    runSearch();
		return null;
	}
  
	// prepare the query and issue the search command
	private void runSearch() 
	{
  		// TODO prepare query string for complex searches & prevent injections
	    results = performSearch(searchString);               
	} 
  
	// run the search and return the records found. 
	private List<Care_plan_step__c> performSearch(string searchString) 
	{
	    String soql = 'select id, name, description__c, Care_Plan_Objective__c, What_step_needs_to_happen_first__c from Care_Plan_Step__c where Care_Plan_Objective__r.Client__c = :clientID and (not ((Reference__c like :attendancePrefix) or Step_Records_Attendance__c=true))';
		if(searchString != '' && searchString != null)
		{
			soql = soql +  ' and name LIKE \'%' + searchString +'%\' ';
			soql = soql + ' order by Care_Plan_Objective__r.Area__c, Name';
		}
		soql = soql + ' limit 200';
		System.debug(soql);
		return database.query(soql); 
	}
  
	// used by the visualforce page to send the link to the right dom element
	public string getFormTag() 
	{
	    return System.currentPageReference().getParameters().get('frm');
	}
    
	// used by the visualforce page to send the link to the right dom element for the text box
	public string getTextBox() 
	{
		return System.currentPageReference().getParameters().get('txt');
	}
}