src/objects/Attendance__c.object
<CustomObject>
    <fields>
        <fullName>Enrolment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Enrolment</label>
        <referenceTo>Enrolment__c</referenceTo>
        <relationshipLabel>Attendances</relationshipLabel>
        <relationshipName>Attendances</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Session__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The program session the client attends</inlineHelpText>
        <label>Program Session</label>
        <referenceTo>Program_Session__c</referenceTo>
        <relationshipLabel>Attendances</relationshipLabel>
        <relationshipName>Attendances</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Young_Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The person who attended the event</inlineHelpText>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Attendances</relationshipLabel>
        <relationshipName>Attendances</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Attendance</label>
    <nameField>
        <label>Attendance Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendances</pluralLabel>
    <recordTypes>
        <fullName>Course_Attendance</fullName>
        <active>true</active>
        <description>Used for program courses</description>
        <label>Course Attendance</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Initials__c</fullName>
        <formula>LEFT (FirstName,1) &amp; LEFT (LastName, 1)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Initials</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Clients</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/eCASS_settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Create_past_attendances__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>On enrolment in a course, create past attendance records</inlineHelpText>
        <label>Create past attendances</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enrolment_Name_Template__c</fullName>
        <defaultValue>&quot;Enr-$NAME$-$DATE$&quot;</defaultValue>
        <inlineHelpText>Format of the enrolment name.
$NAME$ is replaced with the client&apos;s name
$DATE$ is replaced with the Enrolment date (either the Date joined program or the created date)
$INITIALS$ is replaced with the client&apos;s initials
Everything else is left alone</inlineHelpText>
        <label>Enrolment Name Template</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>eCASS settings</label>
</CustomObject>

src/objects/Enrolment__c.object
<CustomObject>
    <fields>
        <fullName>Enrolment_Date__c</fullName>
        <description>This is the date field that may be used in the name of the enrolment</description>
        <formula>if( isblank(Date_joined_program__c), dateValue(CreatedDate),  Date_joined_program__c )</formula>
        <label>Enrolment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program_Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program/Service</label>
        <referenceTo>Program_Service__c</referenceTo>
        <relationshipLabel>Enrolments</relationshipLabel>
        <relationshipName>Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status_on_Programme__c</fullName>
        <label>Status on Programme</label>
        <picklist>
            <picklistValues>
                <fullName>Waiting List</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drop-out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrew</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Young_Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Attendee</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Enrolments</relationshipLabel>
        <relationshipName>Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Enrolment</label>
    <nameField>
        <label>Enrolment Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrolments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program_Service__c.object
<CustomObject>
    <fields>
        <fullName>Total_EnrolmentsV2__c</fullName>
        <inlineHelpText>Number of Students who are Active or have completed this course (excludes those that dropped out)</inlineHelpText>
        <label>Total Enrolments</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Program/Course</label>
    <nameField>
        <label>Program/Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs/Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program_Session__c.object
<CustomObject>
    <fields>
        <fullName>Program_Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program/Service</label>
        <referenceTo>Program_Service__c</referenceTo>
        <relationshipLabel>Program Sessions</relationshipLabel>
        <relationshipName>Program_Sessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Session_Date__c</fullName>
        <label>Session Date</label>
        <type>Date</type>
    </fields>
    <label>Program Session</label>
    <nameField>
        <displayFormat>Session-{DD}/{MM}/{YY}-{00}</displayFormat>
        <label>Program Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EnrolmentsTriggerClass.cls
/*
	Author: Eamon Kelly, Enclude
	Purpose: When a client is enrolled in a course if Create_past_attendances__c is true in the settings, then create attendances for them in the previous sessions
	Also used to count the enrolments in the course to avoid rollups - only active and completed
	Tested in testCreateAttendanceTrigger 
*/
public with sharing class EnrolmentsTriggerClass implements TriggerDispatcher.ITriggerEntry
{
	public void MainEntry (String TriggerObject, Boolean isBefore, Boolean isDelete, Boolean isAfter, Boolean isInsert, Boolean isUpdate, Boolean isExecuting,
		List<SObject> newList, Map<Id, SObject> newMap, List<SObject> oldList, Map<Id, SObject> oldMap)
	{
		if (isInsert)
		{
			if (isBefore) CreateSessionsOnNewEnrolment (newList);
			else if (isAfter)
			{
				ChangeName ((map<Id, Enrolment__c>)newMap);
				CountNumberEnrolled (newList);
			}
		}
		else if (isUpdate)
		{
			if (isAfter) CountNumberEnrolled (newList);
		}
		else if (trigger.isDelete)
		{
			if (isAfter) CountNumberEnrolled (oldList);
		}
	}

	public void ChangeName (map<Id, Enrolment__c> enrMap)
	{
		String nameTemplate = TriggerDispatcher.settings.Enrolment_Name_Template__c;
		list<Enrolment__c>enrolmentsToUpdate = new list<Enrolment__c>();
		for (Enrolment__c oneEnr: [select ID, Name, Young_Person__c, Young_Person__r.Name, Young_Person__r.Initials__c, Enrolment_Date__c from Enrolment__c where ID in :enrMap.keySet()])
		{
			Date enrolmentDate = oneEnr.Enrolment_Date__c != null ? oneEnr.Enrolment_Date__c : system.today();
			String clientName = oneEnr.Young_Person__c != null ? oneEnr.Young_Person__r.Name : '';
			String clientInitials = oneEnr.Young_Person__c != null ? oneEnr.Young_Person__r.Initials__c : '';
			String newName;
			newName = nameTemplate.replace('$NAME$', clientName).replace('$DATE$', enrolmentDate.format()).replace('$INITIALS$', clientInitials);
			if (newName != oneEnr.Name) 
			{
				oneEnr.Name = newName;
				enrolmentsToUpdate.add (oneEnr);
			}
		}
		if (enrolmentsToUpdate.size() > 0) update enrolmentsToUpdate;
	}

	public void CreateSessionsOnNewEnrolment (list<Enrolment__c> newList) 
	{
		Id courseAttendanceRecordTypeId = [select Id from RecordType where sObjectType='Attendance__c' and DeveloperName = 'Course_Attendance'].Id;
		List<Attendance__c> attendanceList = new List<Attendance__c>{};
		Boolean createPastAttendances = false; // turning the default from true to false EK 3/7/13 
		if (newList.size() < 10) // not required for mass import
		{
			eCASS_settings__c settings = eCASS_settings__c.getOrgDefaults();
			if (settings != null && settings.Create_past_attendances__c != null)
				createPastAttendances = settings.Create_past_attendances__c;
			
			for (Enrolment__c oneEnroll: newList)
			{
				// get list of sessions and add an attendance record for each one
				// TODO - for services that run forever, this would create too many past attendances, we need to decide how far back to go
				for (Program_Session__c sess: [select id, Session_Date__c from Program_Session__c where Program_Service__c = :oneEnroll.Program_Service__c])
				{
					if (sess.Session_Date__c < system.today() && createPastAttendances == false) continue;
					Attendance__c oneAttendance = new Attendance__c (Name='FromEnrolment', Program_Session__c=sess.id, Young_Person__c = oneEnroll.Young_Person__c, Enrolment__c=oneEnroll.id, RecordTypeId = courseAttendanceRecordTypeId);
					attendanceList.Add(oneAttendance);
				}
			}
			insert attendanceList;
		}
	}
	
	public void CountNumberEnrolled (List<Enrolment__c> enrList)
	{
		set<id>courses = new set<id>();
		for (Enrolment__c oneEnrol: enrList)
		{
			courses.add (oneEnrol.Program_Service__c);
		}
		// need to count all the enrolments on these sessions
		list<Program_Service__c> progCourses = [SELECT Total_EnrolmentsV2__c, (SELECT Status_on_Programme__c FROM Participants__r where Status_on_Programme__c = 'Active' or Status_on_Programme__c = 'Completed') FROM Program_Service__c where ID in :courses];
		for (Program_Service__c oneCourse: progCourses)
		{
			oneCourse.Total_EnrolmentsV2__c = oneCourse.Participants__r.size();
		}		
		update progCourses;
	}
	
}