src/objects/Attendance__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Type__c</fullName>
        <label>Activity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Brief intervention</fullName>
                </value>
                <value>
                    <fullName>Key Working</fullName>
                </value>
                <value>
                    <fullName>Case Management</fullName>
                </value>
                <value>
                    <fullName>Psychiatric treatment</fullName>
                </value>
                <value>
                    <fullName>Individual counselling</fullName>
                </value>
                <value>
                    <fullName>Group counselling</fullName>
                </value>
                <value>
                    <fullName>Social and/or occupational reintegration</fullName>
                </value>
                <value>
                    <fullName>Family therapy</fullName>
                </value>
                <value>
                    <fullName>Complimentary Therapy</fullName>
                </value>
                <value>
                    <fullName>Genera Admin</fullName>
                </value>
                <value>
                    <fullName>HR</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Interagency meeting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Attendance_Date__c</fullName>
        <description>Return a date depending on the record type</description>
        <formula>CASE( RecordType.DeveloperName , &quot;Course_Attendance&quot;,  Date_of_Session__c , &quot;Drop_In_Attendance&quot;,  Drop_in__r.Date__c , &quot;One_to_One_Attendance&quot;,  DATEVALUE(Date_and_time_of_attendance__c), &quot;Open_Access_Attendance&quot;,  DATEVALUE(Date_and_Time_client_entered__c),  DATEVALUE(CreatedDate) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Attendance Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <formula>Program_Session__r.Program_Service__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Course</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_and_Time_client_entered__c</fullName>
        <label>Date and Time client entered</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_and_Time_client_left__c</fullName>
        <label>Date and Time client left</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_and_time_of_attendance__c</fullName>
        <label>Date and time of attendance</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Drop_in__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Drop-in</label>
        <referenceTo>Drop_in__c</referenceTo>
        <relationshipLabel>Drop-in Attendance</relationshipLabel>
        <relationshipName>Drop_in_Attendance2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Duration_in_minutes__c</fullName>
        <defaultValue>$Setup.eCASS_settings__c.Default_attendance_duration__c</defaultValue>
        <label>Duration (in minutes)</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Programme__c</fullName>
        <label>Programme</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Drug Team</fullName>
                </value>
                <value>
                    <fullName>Cocaine</fullName>
                </value>
                <value>
                    <fullName>Drop-in</fullName>
                </value>
                <value>
                    <fullName>Outreach</fullName>
                </value>
                <value>
                    <fullName>CE Programme</fullName>
                </value>
                <value>
                    <fullName>Family Support</fullName>
                </value>
                <value>
                    <fullName>Aftercare</fullName>
                </value>
                <value>
                    <fullName>Stabisation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Young_Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The person who attended the event</inlineHelpText>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Attendances</relationshipLabel>
        <relationshipName>Attendances</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Attendance</label>
    <nameField>
        <label>Attendance Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendances</pluralLabel>
    <recordTypes>
        <fullName>Course_Attendance</fullName>
        <active>true</active>
        <description>Used for program courses</description>
        <label>Course Attendance</label>
    </recordTypes>
    <recordTypes>
        <fullName>Drop_In_Attendance</fullName>
        <active>true</active>
        <description>Used to record Drop In Attendances</description>
        <label>Drop In Attendance</label>
    </recordTypes>
    <recordTypes>
        <fullName>One_to_One_Attendance</fullName>
        <active>true</active>
        <description>Use for a meeting with a client</description>
        <label>One to One Attendance</label>
    </recordTypes>
    <recordTypes>
        <fullName>Open_Access_Attendance</fullName>
        <active>true</active>
        <description>Used to record for Open Access attendance</description>
        <label>Open Access Attendance</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Full_name__c</fullName>
        <formula>FirstName &amp; &quot; &quot; &amp; LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Full name</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Clients</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Drop_in__c.object
<CustomObject>
    <fields>
        <fullName>Drop_In__c</fullName>
        <label>Drop-In</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Monday Social</fullName>
                </value>
                <value>
                    <fullName>Tuesday AM</fullName>
                </value>
                <value>
                    <fullName>Tuesday PM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Drop-in</label>
    <nameField>
        <label>Drop-in Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drop-in</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CalendarController.cls
/*
	Author: Eamon Kelly, Enclude
	Purpose: Display a client calendar based on the attendance records linked to the client
	Taken from http://www.codebycody.com/2013/06/create-calendar-view-in-salesforcecom.html
	Docs for the FullCalendar plugin are at http://fullcalendar.io/
	Called from: Button on a contact
	Tested in: TestClientCalendar
*/
global with sharing class CalendarController
{
	//Class to hold calendar event data
    global class calEvent
	{
        global String title {get;set;}
        global Boolean allDay {get;set;}
        global String startString {get;set;}
        global String endString {get;set;}
        global String url {get;set;}
        global String className {get;set;}
		global ID id {get;set;}
		global Boolean editable {get;set;}
    }

    //The calendar plugin is expecting dates is a certain format. We can use this string to get it formated correctly
//    String dtFormat = 'EEE, d MMM yyyy HH:mm:ss z';
    String dtFormat = 'yyyy-MM-dd HH:mm:ssZ'; // 2015-10-25T22:34:51Z
 	global Contact client {get;set;}
    global transient list<calEvent> events {get;set;}

	@RemoteAction
	global static String attendanceMoved (String attendanceID, String starttime, String endtime) 
	{
		Attendance__c attToUpdate = [select Id, Date_and_time_of_attendance__c, Date_and_Time_client_entered__c, Date_and_Time_client_left__c, RecordType.DeveloperName from Attendance__c where id = :attendanceID];
		if (attToUpdate != null)
		{
			if (attToUpdate.RecordType.DeveloperName == 'One_to_One_Attendance')
			{
				attToUpdate.Date_and_time_of_attendance__c =  Datetime.valueOf(starttime);
				update attToUpdate;
			}
			else if (attToUpdate.RecordType.DeveloperName == 'Open_Access_Attendance')
			{
				attToUpdate.Date_and_Time_client_entered__c =  Datetime.valueOf(starttime);
				attToUpdate.Date_and_Time_client_left__c =  Datetime.valueOf(endtime);
				update attToUpdate;
			}
		}
		return 'Hi';
	}

	@RemoteAction
	global static String attendanceDurationChanged (String attendanceID, String duration, String endtime) 
	{
		system.debug ('Duration is: ' + duration);
		Attendance__c attToUpdate = [select Id, Duration_in_minutes__c, Date_and_Time_client_left__c, RecordType.DeveloperName from Attendance__c where id = :attendanceID];
		if (attToUpdate != null)
		{
			if (attToUpdate.RecordType.DeveloperName == 'One_to_One_Attendance')
			{
				attToUpdate.Duration_in_minutes__c =  attToUpdate.Duration_in_minutes__c + Integer.valueOf(duration);
				update attToUpdate;
			}
			else if (attToUpdate.RecordType.DeveloperName == 'Open_Access_Attendance')
			{
				attToUpdate.Date_and_Time_client_left__c =  Datetime.valueOf(endtime);
				update attToUpdate;
			}
		}
		return 'Hi';
	}

	global CalendarController(ApexPages.StandardController controller)
    {
        client = [select Id, Full_name__c from Contact where ID = :controller.getID()];
    }

	global pageReference pageLoad ()
	{
		events = new list<calEvent>();
		for (Attendance__c oneAtt : [select id, RecordType.DeveloperName, RecordType.Name, Comment__c, Activity_Type__c, Programme__c, Drop_in__r.Name, Course__c,
			Attendance_Date__c, Date_and_time_of_attendance__c, Duration_in_minutes__c, Date_and_Time_client_entered__c, Date_and_Time_client_left__c
			from Attendance__c where Young_Person__c = :client.Id and Attendance_Date__c != null limit 999])
		{
            calEvent attEvent = new calEvent();
            attEvent.id = oneAtt.Id;
            attEvent.url = '/' + oneAtt.Id;
            attEvent.className = oneAtt.RecordType.DeveloperName;
			if (oneAtt.RecordType.DeveloperName == 'One_to_One_Attendance' && oneAtt.Date_and_time_of_attendance__c != null)
			{
				attEvent.startString = oneAtt.Date_and_time_of_attendance__c.format(dtFormat);
				attEvent.endString = oneAtt.Date_and_time_of_attendance__c.addMinutes ((Integer)oneAtt.Duration_in_minutes__c).format(dtFormat);
		        attEvent.allDay = false;
				attEvent.editable = true;
			}
			else if (oneAtt.RecordType.DeveloperName == 'Open_Access_Attendance' && oneAtt.Date_and_Time_client_entered__c != null)
			{
				attEvent.startString = oneAtt.Date_and_Time_client_entered__c.format(dtFormat);
				attEvent.endString = oneAtt.Date_and_Time_client_left__c != null ? oneAtt.Date_and_Time_client_left__c.format(dtFormat) : oneAtt.Date_and_Time_client_entered__c.addMinutes (60).format(dtFormat);
		        attEvent.allDay = false;
				attEvent.editable = true;
			}
			else
			{
				DateTime startDT = datetime.newInstance(oneAtt.Attendance_Date__c.Year(),oneAtt.Attendance_Date__c.Month(), oneAtt.Attendance_Date__c.Day());
				attEvent.startString = startDT.format(dtFormat);
				attEvent.endString = '';
				attEvent.allDay = true;
				attEvent.editable = false;
			}
			if (oneAtt.RecordType.DeveloperName == 'One_to_One_Attendance' || oneAtt.RecordType.DeveloperName == 'Open_Access_Attendance')
			{
				attEvent.title = SetEventTitle (oneAtt.Programme__c, oneAtt.Activity_Type__c, oneAtt.RecordType.Name);
			}
			else if (oneAtt.RecordType.DeveloperName == 'Drop_In_Attendance')
			{
				attEvent.title = oneAtt.Drop_in__r.Name;
			}
			else if (oneAtt.RecordType.DeveloperName == 'Course_Attendance')
			{
				attEvent.title = oneAtt.Course__c;
			}
            events.add(attEvent);
		}

		return null;
	}

	private string SetEventTitle (String bit1, String bit2, String RecordTypeName)
	{
		String title = RecordTypeName;
		if (bit1 != null) 
		{
			if (bit2 != null)
			{
				title = bit1 + ' - ' + bit2;
			}
			else
			{
				title = bit1;
			}
		}
		else if (bit2 != null)
		{
			title = bit2;
		}
		return title;
	}
}