src/objects/Attendance__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <formula>CASE( RecordType.DeveloperName , &quot;Course_Attendance&quot;,  Course__c  , &quot;Drop_In_Attendance&quot;,  text(Reason_for_Attending__c)  , &quot;One_to_One_Attendance&quot;, text(Reason_for_Attending__c), &quot;Open_Access_Attendance&quot;, &quot;&quot;, null )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Booked</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Attended</fullName>
                </value>
                <value>
                    <fullName>Cancelled with notice and reason</fullName>
                </value>
                <value>
                    <fullName>Cancelled Late</fullName>
                </value>
                <value>
                    <fullName>No Show</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Attendance</label>
    <nameField>
        <label>Attendance Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Care_Plan_Objective__c.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <picklist>
            <picklistValues>
                <fullName>Drug &amp; Alcohol Use</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physical &amp; Psychological Problems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Problems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Functioning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Risk Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Care Plan Administration</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Care Plan Objectives</relationshipLabel>
        <relationshipName>Care_Plan_Objectives1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_objective_set__c</fullName>
        <label>Date objective set</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Next_Review_Date__c</fullName>
        <label>Next Review Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Objective_Status__c</fullName>
        <label>Objective Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Care Plan Objective</label>
    <nameField>
        <label>Care Plan Objective</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Care Plan Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Care_Plan_Review__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Care Plan Reviews</relationshipLabel>
        <relationshipName>Care_Plan_Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_present_at_review__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Client present at review</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Next_Review_Date__c</fullName>
        <label>Next Review Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Review_Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <label>Review Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Summary__c</fullName>
        <inlineHelpText>Notes on how the review went</inlineHelpText>
        <label>Summary</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Care Plan Review</label>
    <nameField>
        <displayFormat>CPR-{YY}/{MM}/{DD}-{000}</displayFormat>
        <label>Care Plan Review Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Plan Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Care_plan_step__c.object
<CustomObject>
    <fields>
        <fullName>Care_Plan_Objective__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Care Plan Objective</label>
        <referenceTo>Care_Plan_Objective__c</referenceTo>
        <relationshipLabel>Care plan steps</relationshipLabel>
        <relationshipName>Care_plan_steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date Step Set</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <description>Reference to the object (attendance or event) that this step refers to - set by trigger</description>
        <label>Reference</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <controllingField>Step_records_attendance__c</controllingField>
            <picklistValues>
                <fullName>Booked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled with notice and reason</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled Late</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>=================</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Step_records_attendance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Step records attendance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>What_step_needs_to_happen_first__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What care plan step needs to happen first?</inlineHelpText>
        <label>What step needs to happen first</label>
        <referenceTo>Care_plan_step__c</referenceTo>
        <relationshipLabel>Care plan steps</relationshipLabel>
        <relationshipName>Care_plan_steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Care plan step</label>
    <nameField>
        <displayFormat>CPS-{00000}</displayFormat>
        <label>Care plan step name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care plan steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <formula>LEFT(TEXT(HSE_area__c), 2)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Area</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Clients</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CarePlanReviewController.cls
/*
	Author: Eamon Kelly, Enclude
	Purpose: Display a care plan and allow steps and reviews to be created
	Called from: Button on Client
	Tested in: TestCarePlanReview
*/
global with sharing class CarePlanReviewController 
{
	global List<Schema.FieldSetMember> goalHeaderFields {get;set;}
	global List<Schema.FieldSetMember> goalFields {get;set;}
	private List<Schema.FieldSetMember> allGoalFields {get;set;}
	private List<Schema.FieldSetMember> allStepFields {get;set;}
	global List<Schema.FieldSetMember> stepTaskFields {get;set;}
	global List<Schema.FieldSetMember> stepAttendanceFields {get;set;}
	private ApexPages.StandardController cpsc;
	private Boolean calledFromStandardPage=false;
	global Contact client {get; set;}
	global Care_Plan_Review__c review {get;set;}
	private list <Care_Plan_Objective__c> internalGoalList; 
	global String attendancePrefix {get;Set;}
	global String careplanstepPrefix {get;Set;}
	global Boolean showAttendanceSteps {get;Set;}
	global list <Care_Plan_Objective__c> goalList 
	{
		get 
		{
			return internalGoalList;
		} 
		set;
	}

	global CarePlanReviewController(ApexPages.StandardController stdController) 
	{
		Initialise ();
		try // to get hold of the client - maybe this is launched from the "New" button on the Care Plan Review home page
		{	        
 			if (apexpages.currentpage().getParameters().get('retURL') != null)
			{
	    		review = (Care_Plan_Review__c)stdController.getRecord();
	    		system.debug ('retURL: ' + apexpages.currentpage().getParameters().get('retURL'));
				String clientID = apexpages.currentpage().getParameters().get('retURL').substring (1,16);
	    		client = [select ID, Name from Contact where Id=:clientID];
			}
			else
			{
				review = [select ID, Name, Client__c, Client_present_at_review__c, Summary__c, Next_Review_Date__c, Review_Date__c from Care_Plan_Review__c where id=:stdController.getID()];
	    		client = [select ID, Name from Contact where Id=:review.Client__c];
			}
		}
		catch (Exception e)
		{
			client = null;
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.WARNING, Label.Care_Plan_Review_without_Client);
            ApexPages.addMessage(myMsg);
		}

		if (apexpages.currentpage().getParameters().get('PRINT') != null)
		{
			if (apexpages.currentpage().getParameters().get('showAttendanceSteps') != null)
			{
				showAttendanceSteps = apexpages.currentpage().getParameters().get('showAttendanceSteps') == 'true';
			} 
			getClientCarePlan ();
		}
     	cpsc = stdController;
    	
	}

	private void Initialise ()
	{
	   	goalHeaderFields = getFields (Schema.SObjectType.Care_Plan_Objective__c.fieldSets.getMap().get(AppConfigSupport.PackagePrefix+'Review_Header_Fields'));
    	goalFields = getFields (Schema.SObjectType.Care_Plan_Objective__c.fieldSets.getMap().get(AppConfigSupport.PackagePrefix+'Review_Fields'));
		allGoalFields = goalHeaderFields.clone();
		allGoalFields.addAll (goalFields);
    	stepTaskFields = getFields (Schema.SObjectType.Care_plan_step__c.fieldSets.getMap().get(AppConfigSupport.PackagePrefix+'Review_Fields'));
    	stepAttendanceFields = getFields (Schema.SObjectType.Care_plan_step__c.fieldSets.getMap().get(AppConfigSupport.PackagePrefix+'Attendance_Review_Fields'));
		allStepFields = mergeFieldSetLists (stepTaskFields, stepAttendanceFields);
		attendancePrefix = Attendance__c.sObjectType.getDescribe().getKeyPrefix();
		careplanstepPrefix = Care_plan_step__c.sObjectType.getDescribe().getKeyPrefix();
		showAttendanceSteps = false;
		if (ApexPages.currentpage().getParameters().get('FromStandardPage') != null)
		{
			calledFromStandardPage = true;
		}
	}

	global PageReference getClientCarePlan ()
	{
		if (client != null)
		{
    		internalGoalList = getObjectives (allGoalFields, allStepFields, client.id);
			if (internalGoalList.size() > 0)
			{
				CountNumberOfEachTypeOfStep (internalGoalList);
			}
			else if (calledFromStandardPage == false)
			{
//				PageReference creationPage = Page.StandardCarePlan;
				PageReference creationPage = Page.StandardCarePlanUsingMetaData;
				creationPage.getParameters().putAll (apexpages.currentpage().getParameters());
				creationPage.getParameters().put('ID', client.id);
				return creationPage;
			}
		}
		return null;
	}

	global PageReference launchStandardCarePlan ()
	{
//		PageReference creationPage = Page.StandardCarePlan;
		PageReference creationPage = Page.StandardCarePlanUsingMetaData;
		creationPage.getParameters().putAll (apexpages.currentpage().getParameters());
	    creationPage.getParameters().put('ID', client.id);
		return creationPage;
	}

	private List<Schema.FieldSetMember> mergeFieldSetLists (List<Schema.FieldSetMember> listA, List<Schema.FieldSetMember> listB)
	{
		Set<Schema.FieldSetMember> mergedSet = new Set<Schema.FieldSetMember>(listA);
		for (Schema.FieldSetMember oneMember : listB)
		{
			Boolean inlistA = false;
			for (Schema.FieldSetMember AMember : listA)
			{
				if (AMember.getFieldPath() == oneMember.getFieldPath()) inlistA = true;
			}
			if (!inlistA)
			{
				mergedSet.add (oneMember);
			}
		}
		return new List<Schema.FieldSetMember>(mergedSet);
	}

	// the default save - just used when launched from the New button on the Care Plan Review home page
	global pageReference Save ()
	{
		cpsc.save();
		client = [select ID, Name from Contact where Id=:review.Client__c];
		getClientCarePlan();
		return null;
	} 

	global pageReference SaveReview ()
	{
		cpsc.save();
		if (internalGoalList != null)
		{
			update internalGoalList;
			UpdateSteps (internalGoalList);
		}
    	internalGoalList = getObjectives (allGoalFields, allStepFields, client.id);
		CountNumberOfEachTypeOfStep (internalGoalList);
   		ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.INFO, Label.Care_Plan_Review_Saved);
        ApexPages.addMessage(myMsg);
		return null;
	} 

	private void UpdateSteps (list <Care_Plan_Objective__c> glList)
	{
		list <Care_Plan_Step__c> stepsToUpdate = new list <Care_Plan_Step__c>();
		for (Care_Plan_Objective__c oneGoal: glList)
		{
			stepsToUpdate.addAll (oneGoal.Care_Plan_Steps__r);
		}
		update stepsToUpdate;
	}
	
	private List<Schema.FieldSetMember> getFields(Schema.FieldSet fs1) 
    {
        if (fs1 == null)
        {
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'No fieldset found for ' + fs1);
            ApexPages.addMessage(myMsg);
            return new list <Schema.FieldSetMember> ();
        } 
        
        List<Schema.FieldSetMember> allFields = fs1.getFields();
        List<Schema.FieldSetMember> returnFields = new List<Schema.FieldSetMember>();
        
        for (Integer i=0; i<allFields.size(); i++)
        {
            returnFields.add (allFields[i]);            
        }
        return returnFields;
    }

    private List<Care_Plan_Objective__c> getObjectives (List<Schema.FieldSetMember> needsFields, List<Schema.FieldSetMember> stepsFields, ID clientID)
    {
        String soql = getSelectStatement (needsFields);
        String stepSoql = getSelectStatement (stepsFields);
        soql += ', Area__c, Number_of_Task_Steps__c, Number_of_Attendance_Steps__c, (' + stepSoql + ' , Description__c, Reference__c, Step_Records_Attendance__c, What_step_needs_to_happen_first__c from Care_plan_steps__r where Status__c != \'Completed\' order by Date__c asc, Name)';
        soql += ' from Care_Plan_Objective__c where Client__c=:clientID and Objective_Status__c != \'Closed\' order by Area__c, Date_objective_set__c asc';
        
        List<Care_Plan_Objective__c> allObjectives = database.query(soql);
        
        return allObjectives;
    }
    
    private static String getSelectStatement (List<Schema.FieldSetMember> fieldList)
    {
        String query = 'SELECT ';
        for(Schema.FieldSetMember f : fieldList) 
        {
            query += f.getFieldPath() + ', ';
        }
        query += 'Name, ID ';
        return query;
    }

	global void ShowAttSteps ()
	{
		showAttendanceSteps = true;
	}

	global void HideAttSteps ()
	{
		showAttendanceSteps = false;
	}

	private void CountNumberOfEachTypeOfStep (List<Care_Plan_Objective__c> goals)
	{
		for (Care_Plan_Objective__c oneGoal : goals)
		{
			oneGoal.Number_of_Task_Steps__c = 0;
			oneGoal.Number_of_Attendance_Steps__c = 0;
			for (Care_plan_step__c oneStep : oneGoal.Care_plan_steps__r)
			{
				if (oneStep.Reference__c != null && oneStep.Reference__c.startsWith (attendancePrefix)) 
				{
					oneGoal.Number_of_Attendance_Steps__c++;
					oneStep.Step_Records_Attendance__c = true;
				}
				else 
				{
					oneGoal.Number_of_Task_Steps__c++;
					oneStep.Step_Records_Attendance__c = false;
				}
			}
		}
	}
}