src/objects/Care_Plan_Objective__c.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <picklist>
            <picklistValues>
                <fullName>Drug &amp; Alcohol Use</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physical &amp; Psychological Problems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Problems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Functioning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Risk Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Care Plan Administration</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Care Plan Objectives</relationshipLabel>
        <relationshipName>Care_Plan_Objectives1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Care Plan Objective</label>
    <nameField>
        <label>Care Plan Objective</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Care Plan Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Care_Plan_Review__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Care Plan Reviews</relationshipLabel>
        <relationshipName>Care_Plan_Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Care Plan Review</label>
    <nameField>
        <displayFormat>CPR-{YY}/{MM}/{DD}-{000}</displayFormat>
        <label>Care Plan Review Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Plan Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Care_plan_step__c.object
<CustomObject>
    <fields>
        <fullName>Care_Plan_Objective__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Care Plan Objective</label>
        <referenceTo>Care_Plan_Objective__c</referenceTo>
        <relationshipLabel>Care plan steps</relationshipLabel>
        <relationshipName>Care_plan_steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Step_records_attendance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Step records attendance</label>
        <type>Checkbox</type>
    </fields>
    <label>Care plan step</label>
    <nameField>
        <displayFormat>CPS-{00000}</displayFormat>
        <label>Care plan step name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care plan steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <formula>LEFT(TEXT(HSE_area__c), 2)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Area</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Clients</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestCarePlanReview.cls
/*
	Author: Eamon Kelly, Enclude
	Purpose: Display a care plan and allow steps and reviews to be created
	Called from: Button on Client
*/
@isTest
public class TestCarePlanReview 
{ 
	public static testmethod Care_Plan_Review__c TestReviewCreation ()
	{
	    Contact youngPerson = new Contact (LastName = 'Kelly');
        insert youngPerson;

        Care_Plan_Objective__c careplan = new Care_Plan_Objective__c (Client__c=youngPerson.id, Area__c='Legal', Name='Test');
		insert careplan;

		Care_Plan_Step__c attstep = new Care_plan_step__c (Care_Plan_Objective__c=careplan.id, Step_Records_Attendance__c=true);
		insert attstep;

		Care_Plan_Step__c taskstep = new Care_plan_step__c (Care_Plan_Objective__c=careplan.id, Step_Records_Attendance__c=false);
		insert taskstep;

 		Test.setCurrentPageReference(new PageReference('Page.CarePlanReview')); 
		System.currentPageReference().getParameters().put('retURL', '/' + youngPerson.id);

		Care_Plan_Review__c careplanreview = new Care_Plan_Review__c (Client__c=youngPerson.Id);
		ApexPages.StandardController programController = new ApexPages.StandardController(careplanreview);
    	CarePlanReviewController cprc = new CarePlanReviewController (programController);
		cprc.SaveReview();

		list <Care_Plan_Review__c> cprs = [select ID, Client__c from Care_Plan_Review__c where Client__c = :youngPerson.Id];
		system.assertEquals (1, cprs.size());
		return cprs[0];
	}

	public static testmethod void TestReviewEditting ()
	{
		Care_Plan_Review__c cpr = TestReviewCreation ();

		ApexPages.StandardController programController = new ApexPages.StandardController(cpr);
    	CarePlanReviewController cprc = new CarePlanReviewController (programController);
		cprc.SaveReview();

		list <Care_Plan_Review__c> cprs = [select ID from Care_Plan_Review__c];
		system.assertEquals (1, cprs.size());

	}

	public static testmethod void TestLookupController ()
	{
		Care_Plan_Review__c cpr = TestReviewCreation ();

 		Test.setCurrentPageReference(new PageReference('Page.CustomCarePlanStepLookup')); 
		System.currentPageReference().getParameters().put('clientID', cpr.Client__c);
		System.currentPageReference().getParameters().put('lksrch', 'CPS');

		CustomCarePlanStepLookupController lookup = new CustomCarePlanStepLookupController ();
		lookup.Search ();

		system.assertEquals (1, lookup.results.size());
	}
}