src/objects/Care_Plan_Objective__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Care Plan Objectives</relationshipLabel>
        <relationshipName>Care_Plan_Objectives1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Care Plan Objective</label>
    <nameField>
        <label>Care Plan Objective</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Care Plan Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Clients</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestCarePlanObjectiveCreation.cls
/*
	Author: Eamon Kelly, Enclude
	Purpose: Create a goal
	Called from: Override of new goal 
*/
@isTest
public class TestCarePlanObjectiveCreation 
{ 
	public static testmethod void TestCreation ()
	{
	    Contact youngPerson = new Contact (LastName = 'Kelly');
        insert youngPerson;
        
        Care_Plan_Objective__c careplan = new Care_Plan_Objective__c ();

 		Test.setCurrentPageReference(new PageReference('Page.CarePlanObjectiveCreation')); 
		System.currentPageReference().getParameters().put('CLIENT', youngPerson.id);

    	ApexPages.StandardController programController = new ApexPages.StandardController(careplan);
    	CarePlanObjectiveCreation cpoc = new CarePlanObjectiveCreation (programController);
		cpoc.save();
		
		list <Care_Plan_Objective__c> createdObjectives = [select ID from Care_Plan_Objective__c where Client__c = :youngPerson.id];
		system.assertEquals (1, createdObjectives.size());
	}

}