src/objects/Care_Plan_Objective__c.object
<CustomObject>
    <label>Care Plan Objective</label>
    <nameField>
        <label>Care Plan Objective</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Care Plan Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Enrolment__c.object
<CustomObject>
    <fields>
        <fullName>Care_Plan_Objective__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Care Plan Objective</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Care_Plan_Objective__c.Client__c</field>
                <operation>equals</operation>
                <valueField>$Source.Young_Person__c</valueField>
            </filterItems>
            <infoMessage>Showing only care plan objectives for this attendee</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Care_Plan_Objective__c</referenceTo>
        <relationshipLabel>Enrolments on courses</relationshipLabel>
        <relationshipName>Enrolments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_joined_program__c</fullName>
        <label>Date joined program</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program_Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program/Service</label>
        <referenceTo>Program_Service__c</referenceTo>
        <relationshipLabel>Enrolments</relationshipLabel>
        <relationshipName>Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Young_Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Attendee</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Enrolments</relationshipLabel>
        <relationshipName>Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Enrolment</label>
    <nameField>
        <label>Enrolment Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrolments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program_Service__c.object
<CustomObject>
    <label>Program/Course</label>
    <nameField>
        <label>Program/Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs/Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CloneProgramCourse.cls
/*
	Author: Eamon Kelly, Enclude
	Purpose: Create a copy of a program/course with all its enrolments
	Called from: Button on program/course page
	Tested in: TestCloneProgramCourse

Security note: This class is global so that it can be used in customisations for the client - usually via a modified Visualforce page depending on their
					definition of what fields the customer wants copied to the clone
*/
global with sharing class CloneProgramCourse 
{
	public Program_Service__c ps;
    global CloneProgramCourse(ApexPages.StandardController controller)
    {
        ps = (Program_Service__c)controller.getRecord();
    }

	global PageReference DoClone ()
	{
		Program_Service__c clonePS = ps.clone(false, true);
		insert clonePS;

		list <Enrolment__c> clonedEnrolments = new list <Enrolment__c>();
		for (Enrolment__c oldEnrolment : [select id, Name, Young_Person__c, Care_Plan_Objective__c, Date_joined_program__c from Enrolment__c where Program_Service__c = :ps.id])
		{
			Enrolment__c clonedEnrolment = oldEnrolment.clone (false, true);
			clonedEnrolment.Program_Service__c = clonePS.id;
			clonedEnrolments.add (clonedEnrolment);
		}
		
		insert clonedEnrolments;
		
        String clonePSURL = '/' + clonePS.ID + '/e?retURL=%2F' + clonePS.ID;
        PageReference clonePSPage = new PageReference(clonePSURL);
        return clonePSPage;
	}
}