src/objects/Care_Plan_Obj_Template__c.object
<CustomObject>
    <description>When a standard care plan is created, these objectives will be copied into that plan</description>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <picklist>
            <picklistValues>
                <fullName>Drug Use</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alcohol Use</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accomodation/Independent Living</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mental Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physical Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Justice and Legal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family and Relationships</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education and Training</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Objective_Note__c</fullName>
        <label>Objective Note</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Objective_Status__c</fullName>
        <label>Objective Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Care Plan Obj Template</label>
    <nameField>
        <label>Care Plan Obj Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Care Plan Obj Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Care_Plan_Objective__c.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <picklist>
            <picklistValues>
                <fullName>Drug &amp; Alcohol Use</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physical &amp; Psychological Problems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Problems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Functioning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Risk Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Care Plan Administration</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Care Plan Objectives</relationshipLabel>
        <relationshipName>Care_Plan_Objectives1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Objective_Status__c</fullName>
        <label>Objective Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Care Plan Objective</label>
    <nameField>
        <label>Care Plan Objective</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Care Plan Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Care_plan_step__c.object
<CustomObject>
    <fields>
        <fullName>Care_Plan_Objective__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Care Plan Objective</label>
        <referenceTo>Care_Plan_Objective__c</referenceTo>
        <relationshipLabel>Care plan steps</relationshipLabel>
        <relationshipName>Care_plan_steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_of_What_Needs_Template__c</fullName>
        <description>This is the ID of the step template referenced by &quot;What step needs to happen first&quot;</description>
        <label>ID of What Needs Template</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_of_template__c</fullName>
        <description>This is the ID of the template used to create this step</description>
        <label>ID of template</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <controllingField>Step_records_attendance__c</controllingField>
            <picklistValues>
                <fullName>Booked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled with notice and reason</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled Late</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>=================</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>What_step_needs_to_happen_first__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What care plan step needs to happen first?</inlineHelpText>
        <label>What step needs to happen first</label>
        <referenceTo>Care_plan_step__c</referenceTo>
        <relationshipLabel>Care plan steps</relationshipLabel>
        <relationshipName>Care_plan_steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Care plan step</label>
    <nameField>
        <displayFormat>CPS-{00000}</displayFormat>
        <label>Care plan step name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care plan steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <formula>LEFT(TEXT(HSE_area__c), 2)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Area</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Clients</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CPO_Template__mdt.object
<CustomObject>
    <description>When a standard care plan is created, these objectives will be copied into that plan</description>
    <fields>
        <fullName>Area__c</fullName>
        <inlineHelpText>One of:
Drug Use
Alcohol Use
Accomodation/Independent Living
Mental Health
Physical Health
Justice and Legal
Family and Relationships
Finance
Employment
Education and Training</inlineHelpText>
        <label>Area</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Include_this__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Tick to include this objective in the care plan</inlineHelpText>
        <label>Include this objective</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Objective_Note__c</fullName>
        <label>Objective Note</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Objective_Status__c</fullName>
        <defaultValue>&quot;In Progress&quot;</defaultValue>
        <inlineHelpText>One of:
Draft
In Progress
Blocked
Closed</inlineHelpText>
        <label>Objective Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Obsolete__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If ticked, then this care plan objective will not appear in the list of standard objectives</inlineHelpText>
        <label>Obsolete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <defaultValue>&quot;Medium&quot;</defaultValue>
        <inlineHelpText>One of:
Low
Medium
High</inlineHelpText>
        <label>Priority</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Care Plan Objective Template</label>
    <pluralLabel>Care Plan Objective Templates</pluralLabel>
</CustomObject>

src/objects/CPS_Template__mdt.object
<CustomObject>
    <description>When a standard care plan is created and the care plan objective template used, these steps are also copied to the new care plan</description>
    <fields>
        <fullName>Care_Plan_Obj_Template__c</fullName>
        <inlineHelpText>The name of the Care Plan Objective Template</inlineHelpText>
        <label>Care Plan Objective Template</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Creation_Order__c</fullName>
        <inlineHelpText>This is the order the steps will be created in, to all the &quot;What step needs to happen first&quot; step to exist when this step is created</inlineHelpText>
        <label>Creation Order</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>This is effectively the title of the care plan step</inlineHelpText>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Include_this__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Tick to include this step in the care plan</inlineHelpText>
        <label>Include this step</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Obsolete__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If ticked, then this care plan step will not appear in the list of standard steps</inlineHelpText>
        <label>Obsolete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&quot;Open&quot;</defaultValue>
        <inlineHelpText>One of:
Open
Blocked
Completed</inlineHelpText>
        <label>Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>What_step_needs_to_happen_first__c</fullName>
        <inlineHelpText>The name of the care plan step that needs to happen before this one - USE the step&apos;s OBJECT NAME field</inlineHelpText>
        <label>What step needs to happen first</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Care Plan Step Template</label>
    <pluralLabel>Care Plan Step Templates</pluralLabel>
</CustomObject>

src/classes/StandardCarePlanControllerUsingMetaData.cls
/*
	Author: Eamon Kelly, Enclude
	Purpose: Create a standard care plan by copying all and care plan objective templates and steps and associating them with the client
	Called from: Button on client launches StandardCarePlan.page  
	Tested in: TestStandardCarePlanCreation
*/
global class StandardCarePlanControllerUsingMetaData 
{ 
	global class stepWrapper
	{
		global Boolean bIncludeThisStep {get;set;}
		global CPS_Template__mdt thisStep {get;set;}
		global stepWrapper (CPS_Template__mdt aStep)
		{
			thisStep = aStep;
			bIncludeThisStep = thisStep.Include_this__c;
		}
	}

	global class goalWrapper
	{
		global Boolean bIncludeThisGoal {get;set;}
		global CPO_Template__mdt thisGoal {get;set;}
		global goalWrapper (CPO_Template__mdt aGoal)
		{
			thisGoal = aGoal;
			bIncludeThisGoal = thisGoal.Include_this__c;
		}
	}

	private Map<String, Schema.sObjectField> goalFields {get;set;}
	private Map<String, Schema.sObjectField> stepFields {get;set;}
	private Contact client;
	global list <goalWrapper> goalList {get;Set;}
	global list <stepWrapper> stepList {get;Set;}
	private map <String, ID> nameOfStepToID;
	global StandardCarePlanControllerUsingMetaData(ApexPages.StandardController stdController) 
	{
   		system.debug ('Params: ' + apexpages.currentpage().getParameters());

		client = (Contact)stdController.getRecord();
    	goalFields = Schema.SObjectType.CPO_Template__mdt.fields.getMap();
    	stepFields = Schema.SObjectType.CPS_Template__mdt.fields.getMap();
    	createGoalList ();
		createStepList ();
	}

	private void createGoalList ()
	{
		list<CPO_Template__mdt> goals = [select Id, DeveloperName, MasterLabel, Area__c, Include_this__c, Objective_Note__c, Objective_Status__c, Priority__c
			from CPO_Template__mdt where Obsolete__c = false order by Area__c];
		goalList = new list<goalWrapper>();
		for (CPO_Template__mdt oneGoal : goals)
		{
			goalList.add (new goalWrapper (oneGoal));
		}
	}
	
	private void createStepList ()
	{
		list <CPS_Template__mdt> steps = [select Id, DeveloperName, MasterLabel, Care_Plan_Obj_Template__c, Include_this__c, Description__c, What_step_needs_to_happen_first__c, Status__c 
			from CPS_Template__mdt where Obsolete__c = false order by Care_Plan_Obj_Template__c, Creation_Order__c]; 
		nameOfStepToID = new map <String, ID> ();
		stepList = new list<stepWrapper>();
		for (CPS_Template__mdt oneStep : steps)
		{
			nameOfStepToID.put (oneStep.DeveloperName, oneStep.id);
			stepList.add (new stepWrapper (oneStep));
		}
	}
	
	global PageReference CreateCarePlan ()
	{
		AddObjectives ();
		return GoToReview ();
	}

	global PageReference AddObjectives ()
	{
		list <Care_plan_step__c> stepsToCreate = new list <Care_plan_step__c>();
		for (goalWrapper oneGoal : goalList)
		{
			if (oneGoal.bIncludeThisGoal)
			{
				// clone this objective as it has been selected
				Care_Plan_Objective__c newObjective = new Care_Plan_Objective__c (Client__c=client.id, Name=oneGoal.thisGoal.MasterLabel);
				for(Schema.sObjectField f : goalFields.values()) 
				{
					if (f.getDescribe().isCustom() && f.getDescribe().getName() != AppConfigSupport.PackagePrefix+'Include_this__c')
					{
						newObjective.put(f.getDescribe().getName(), oneGoal.thisGoal.get(f.getDescribe().getName()));
					}						
		        }
				insert newObjective; // there will never be more than five or six standard care plan objectives, so safe to do an insert here

				// Now clone the steps selected
				for (stepWrapper oneStep : stepList)
				{
					if (oneStep.bIncludeThisStep && oneStep.thisStep.Care_Plan_Obj_Template__c == oneGoal.thisGoal.DeveloperName)
					{
						Care_Plan_Step__c newStep = new Care_Plan_Step__c (Care_Plan_Objective__c = newObjective.Id, ID_of_template__c=oneStep.thisStep.Id, ID_of_What_Needs_Template__c = nameOfStepToID.get (oneStep.thisStep.What_step_needs_to_happen_first__c)); 
						for(Schema.sObjectField f : stepFields.values()) 
						{
							if (f.getDescribe().isCustom() && f.getDescribe().getName() != AppConfigSupport.PackagePrefix+'Include_this__c' 
								&& f.getDescribe().getName() != AppConfigSupport.PackagePrefix+'Care_Plan_Obj_Template__c' && f.getDescribe().getName() != AppConfigSupport.PackagePrefix+'Creation_Order__c' 
								&& f.getDescribe().getName() != AppConfigSupport.PackagePrefix+'What_step_needs_to_happen_first__c')
							{
								newStep.put(f.getDescribe().getName(), oneStep.thisStep.get(f.getDescribe().getName()));
							}						
				        }
						stepsToCreate.add (newStep);
					}
				}
			}
		}
		if (stepsToCreate.size() > 0) 
		{
			insert stepsToCreate;
			// need to link the steps together
			LinkSteps (stepsToCreate);
		}
		return null;
	}

	global PageReference GoToReview ()
	{
		PageReference reviewPage = Page.CarePlanReview;
		reviewPage.getParameters().putAll (apexpages.currentpage().getParameters());
	    reviewPage.getParameters().put('ID', null);
	    reviewPage.getParameters().put('FromStandardPage', 'true');
		return reviewPage;
	}

	private void LinkSteps (list <Care_plan_step__c> stepsToLink)
	{
		// for all the steps, if the ID_of_What_Needs_Template__c is populated, then find the step that this refers to using ID_of_template__c and link it to this step
		// start with a map of the templates to the steps
		map <Id, Care_plan_step__c> templatesToStepsMap = new map <Id, Care_plan_step__c> ();
		for (Care_plan_step__c oneStep : stepsToLink)
		{
			templatesToStepsMap.put (oneStep.ID_of_template__c, oneStep);
		}
		// now go through all the steps making the connection
		for (Care_plan_step__c oneStep : stepsToLink)
		{
			if (oneStep.ID_of_What_Needs_Template__c != null)
			{
				oneStep.What_step_needs_to_happen_first__c = templatesToStepsMap.get (oneStep.ID_of_What_Needs_Template__c).Id;
			}
		}
		update stepsToLink;
	}
}