src/objects/Care_Plan_Objective__c.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <picklist>
            <picklistValues>
                <fullName>Drug &amp; Alcohol Use</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physical &amp; Psychological Problems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Problems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Functioning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Risk Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Care Plan Administration</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Care Plan Objectives</relationshipLabel>
        <relationshipName>Care_Plan_Objectives1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_completed__c</fullName>
        <label>Date completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_objective_set__c</fullName>
        <label>Date objective set</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>How_will_progress_be_measured__c</fullName>
        <inlineHelpText>Indicators of change. reduction of use of heroine to 40ml in four months</inlineHelpText>
        <label>How will progress be measured</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Latest_Outcome__c</fullName>
        <label>Latest Outcome</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Lead_Agency_name__c</fullName>
        <label>Lead Agency name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Next_Review_Date__c</fullName>
        <label>Next Review Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Objective_Status__c</fullName>
        <label>Objective Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Objective_and_Timescale__c</fullName>
        <label>Objective and Timescale</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Outcome__c</fullName>
        <label>Outcome</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Tools_used__c</fullName>
        <inlineHelpText>e.g. Use Pattern Chart or TOPS or data from metadone clinic!</inlineHelpText>
        <label>Tools: How are we going to measure this?</label>
        <type>TextArea</type>
    </fields>
    <label>Care Plan Objective</label>
    <nameField>
        <label>Care Plan Objective</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Care Plan Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Care_plan_step__c.object
<CustomObject>
    <fields>
        <fullName>Care_Plan_Objective__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Care Plan Objective</label>
        <referenceTo>Care_Plan_Objective__c</referenceTo>
        <relationshipLabel>Care plan steps</relationshipLabel>
        <relationshipName>Care_plan_steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date Step Set</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person_Responsible_for_Action__c</fullName>
        <label>Person Responsible for Action</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <description>Reference to the object (attendance or event) that this step refers to - set by trigger</description>
        <label>Reference</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status_Comment__c</fullName>
        <label>Status Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <controllingField>Step_records_attendance__c</controllingField>
            <picklistValues>
                <fullName>Booked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled with notice and reason</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled Late</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>=================</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>What_step_needs_to_happen_first__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What care plan step needs to happen first?</inlineHelpText>
        <label>What step needs to happen first</label>
        <referenceTo>Care_plan_step__c</referenceTo>
        <relationshipLabel>Care plan steps</relationshipLabel>
        <relationshipName>Care_plan_steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Care plan step</label>
    <nameField>
        <displayFormat>CPS-{00000}</displayFormat>
        <label>Care plan step name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care plan steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <formula>LEFT(TEXT(HSE_area__c), 2)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Area</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Counsellor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Counsellor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Clients</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ViewCarePlanExtension.cls
/*
	Author: Eamon Kelly, Enclude
	Purpose: additions to the care plan to support care care plan domains - each care plan objective can be part of one of six care plan domains
	Called from CarePlanOverview  - a version of the care plan that groups the objectives by domain
*/

public with sharing class ViewCarePlanExtension 
{
    public List<Care_Plan_Objective__c> carePlanGoalsAdmin {get;set;}
    public List<Care_Plan_Objective__c> carePlanGoalsDrugAlcoholUse {get;set;}
    public List<Care_Plan_Objective__c> carePlanGoalsPhysical {get;set;}
    public List<Care_Plan_Objective__c> carePlanGoalsLegal {get;set;}
    public List<Care_Plan_Objective__c> carePlanGoalsSocial {get;set;}
    public List<Care_Plan_Objective__c> carePlanGoalsRisk {get;set;}
    
    ID recordID;
    String recordName;
    public String CaseManager {get;set;}

	public Boolean showInternal {get;set;}
	
	public ViewCarePlanExtension (ApexPages.StandardController controller) 
    {
        sObject con = controller.getRecord();
        recordID = con.id;
        Contact client = [select Name, Counsellor__r.Name from Contact where id = :con.id];
        if (client != null)
        {
            recordName = client.Name;
            CaseManager = client.Counsellor__r.Name;
        }
 
        carePlanGoalsAdmin = getCarePlanGoals ('Care Plan Administration');
        carePlanGoalsDrugAlcoholUse = getCarePlanGoals ('Drug & Alcohol Use');
        carePlanGoalsPhysical = getCarePlanGoals ('Physical & Psychological Problems');
        carePlanGoalsLegal = getCarePlanGoals ('Legal Problems');
        carePlanGoalsSocial = getCarePlanGoals ('Social Functioning');
        carePlanGoalsRisk = getCarePlanGoals ('Risk Assessment');
     }
    
    private List <Care_Plan_Objective__c> getCarePlanGoals (String area)
    {
         List <Care_Plan_Objective__c>carePlanObjectives = [SELECT ID, Name, Latest_Outcome__c, Outcome__c, Objective_and_Timescale__c, Date_objective_set__c, Next_Review_Date__c, 
         	Date_completed__c, Objective_Status__c, How_will_progress_be_measured__c, Tools_used__c, Lead_Agency_name__c,
	         (SELECT ID, Name, Description__c, Person_Responsible_for_Action__c, Date__c, Status__c, Status_Comment__c
	          FROM Care_plan_steps__r order by Date__c DESC, Description__c DESC)
              FROM Care_Plan_Objective__c 
              where Client__c = :recordID and Area__c = :area and (Objective_Status__c = 'In Progress' or Objective_Status__c = 'Draft' or Objective_Status__c = 'Blocked') 
              order by CreatedDate DESC, Date_objective_set__c DESC, Name DESC];
        
   		return carePlanObjectives;
    }
    
    public PageReference printCarePlan ()
	{
		PageReference pdf = new PageReference ('/apex/' +  AppConfigSupport.CarePlanOverviewPrintPage);
		return pdf;
	}
	
    public static testMethod void testViewCarePlan()
    {
        Contact youngPerson = new Contact (LastName = 'Kelly');
        insert youngPerson;
        
        Care_Plan_Objective__c careplan = new Care_Plan_Objective__c (Name='Improve welbeing', Client__c=youngPerson.id, Area__c = 'Drug & Alcohol Use',Objective_Status__c = 'In Progress');
        insert careplan;
        
        Event e1 = new Event (WhoID=youngPerson.id, OwnerID=UserInfo.getUserId(), WhatID=careplan.id, Subject='Test', StartDateTime=DateTime.newInstance(2012,1,5,12,30,30), EndDateTime=DateTime.newInstance(2012,1,5,13,30,30));
        insert e1;
        
        Integer carePlanSteps = [select count() from Care_plan_step__c where Reference__c != null];
        system.assertEquals(1, carePlanSteps);
        
        ApexPages.StandardController contactController = new ApexPages.StandardController(youngPerson);
        ViewCarePlanExtension vc = new ViewCarePlanExtension (contactController);
        vc.printCarePlan();
    }
}