src/objects/Care_Plan_Objective__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Care Plan Objectives</relationshipLabel>
        <relationshipName>Care_Plan_Objectives1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Comment_Reasons_achieved_or_not__c</fullName>
        <label>Comment: Reasons achieved or not!</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Date_completed__c</fullName>
        <label>Date completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_objective_set__c</fullName>
        <label>Date objective set</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>How_will_progress_be_measured__c</fullName>
        <inlineHelpText>Indicators of change. reduction of use of heroine to 40ml in four months</inlineHelpText>
        <label>How will progress be measured</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Lead_Agency_name__c</fullName>
        <label>Lead Agency name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Key_Worker_name__c</fullName>
        <label>Lead Key Worker name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Next_Review_Date__c</fullName>
        <label>Next Review Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Objective_Status__c</fullName>
        <label>Objective Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Objective_and_Timescale__c</fullName>
        <label>Objective and Timescale</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Outcome__c</fullName>
        <label>Outcome</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Referred_to__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referred to</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Care Plan Objectives</relationshipLabel>
        <relationshipName>Care_Plan_Objectives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time_Frame_short__c</fullName>
        <label>Time Frame (short)</label>
        <picklist>
            <picklistValues>
                <fullName>Short-term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium-term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Long-term</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Work_to_be_done_to_achieve_objective__c</fullName>
        <label>Work to be done to achieve objective</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Care Plan Objective</label>
    <nameField>
        <label>Care Plan Objective</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Care Plan Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Care_plan_step__c.object
<CustomObject>
    <fields>
        <fullName>Care_Plan_Objective__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Care Plan Objective</label>
        <referenceTo>Care_Plan_Objective__c</referenceTo>
        <relationshipLabel>Care plan steps</relationshipLabel>
        <relationshipName>Care_plan_steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date Step Set</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person_Responsible_for_Action__c</fullName>
        <label>Person Responsible for Action</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_Organisation__c</fullName>
        <label>Related Organisation</label>
        <picklist>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status_Comment__c</fullName>
        <label>Status Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <controllingField>Step_records_attendance__c</controllingField>
            <picklistValues>
                <fullName>Booked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled with notice and reason</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled Late</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>=================</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>What_step_needs_to_happen_first__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What care plan step needs to happen first?</inlineHelpText>
        <label>What step needs to happen first</label>
        <referenceTo>Care_plan_step__c</referenceTo>
        <relationshipLabel>Care plan steps</relationshipLabel>
        <relationshipName>Care_plan_steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Care plan step</label>
    <nameField>
        <displayFormat>CPS-{00000}</displayFormat>
        <label>Care plan step name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care plan steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Counsellor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Counsellor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Clients</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ViewCarePlan.cls
/*
	Author: Eamon Kelly, Enclude
	Purpose: Displays the complete care plan for one client. 
	Security note: This class is global so that it can be used in customisations for the client - usually via a modified Visualforce page depending on their
					definition of what a careplan should look like
	Called from: CarePlanPage and the CarePlanPrintPage (the PDF version)
	TODO: The next version will used field sets to control the fields that are displayed in the CarePlanPage
*/
global with sharing class ViewCarePlan 
{
    public List<Care_Plan_Objective__c> carePlanObjectives = new List<Care_Plan_Objective__c>();
    public ID recordID;
    public String recordName;
    global String counsellor {get;set;}
    
    global ViewCarePlan (ApexPages.StandardController controller) 
    {
        sObject con = controller.getRecord();
        recordID = con.id;
        Contact client = [select Name, Counsellor__r.Name from Contact where id = :con.id];
        if (client != null)
        {
            recordName = client.Name;
            counsellor = client.Counsellor__r.Name;
        }
        
        carePlanObjectives = [SELECT ID, Name, Comment_Reasons_achieved_or_not__c, Date_completed__c, Date_objective_set__c, How_will_progress_be_measured__c,
            Lead_Agency_name__c, Lead_Key_Worker_name__c, Next_Review_Date__c, Objective_and_Timescale__c, Objective_Status__c, Outcome__c, Referred_to__c, Time_Frame_short__c,
            Work_to_be_done_to_achieve_objective__c, 
            (select ID, Name, Date__c, Description__c, Status__c, Status_Comment__c, Person_Responsible_for_Action__c, Related_Organisation__c from Care_plan_steps__r order by Date__c DESC)
               FROM Care_Plan_Objective__c where Client__c = :recordID order by CreatedDate DESC, Date_objective_set__c DESC];
    }
    
    global List<Care_Plan_Objective__c> getCarePlanObjectives() 
    {
        return carePlanObjectives;
    }
    
    global List<Care_plan_step__c> getCarePlanSteps() // deprecated 
    {
        return null;
    }

	global PageReference printCarePlan ()
	{
		PageReference pdf = new PageReference ('/apex/' + AppConfigSupport.CarePlanPrintPage);
		return pdf;
	}
	
	// Tests start here
    public static testMethod ViewCarePlan testViewCarePlan()
    {
        Contact youngPerson = new Contact (LastName = 'Kelly');
        insert youngPerson;
        
        Care_Plan_Objective__c careplan = new Care_Plan_Objective__c (Name='Improve welbeing', Client__c=youngPerson.id);
        insert careplan;
        
        Event e1 = new Event (WhoID=youngPerson.id, OwnerID=UserInfo.getUserId(), WhatID=careplan.id, Subject='Test', StartDateTime=DateTime.newInstance(2012,1,5,12,30,30), EndDateTime=DateTime.newInstance(2012,1,5,13,30,30));
        insert e1;
        
        ApexPages.StandardController contactController = new ApexPages.StandardController(youngPerson);
        return new ViewCarePlan (contactController);
    }
    
    public static testMethod void testRemainingBits ()
    {
        ViewCarePlan thisClass = testViewCarePlan();
        system.assertEquals (1, thisClass.getCarePlanObjectives().size());
        thisClass.getCarePlanSteps(); // deprecated function - the care plan steps are now accessed via the care plan objectives
        system.assertEquals (1, thisClass.getCarePlanObjectives()[0].Care_plan_steps__r.size());
        thisClass.printCarePlan ();
    }

}