src/objects/Care_Plan_Objective__c.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <picklist>
            <picklistValues>
                <fullName>Drug &amp; Alcohol Use</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physical &amp; Psychological Problems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Problems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Functioning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Risk Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Care Plan Administration</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Care Plan Objectives</relationshipLabel>
        <relationshipName>Care_Plan_Objectives1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Care Plan Objective</label>
    <nameField>
        <label>Care Plan Objective</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Care Plan Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Care_plan_step__c.object
<CustomObject>
    <fields>
        <fullName>Care_Plan_Objective__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Care Plan Objective</label>
        <referenceTo>Care_Plan_Objective__c</referenceTo>
        <relationshipLabel>Care plan steps</relationshipLabel>
        <relationshipName>Care_plan_steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Care plan step</label>
    <nameField>
        <displayFormat>CPS-{00000}</displayFormat>
        <label>Care plan step name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care plan steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <formula>LEFT(TEXT(HSE_area__c), 2)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Area</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestCarePlanStepCreation.cls
/*
	Author: Eamon Kelly, Enclude
	Purpose: Create a step
	Called from: Override of new step 
*/
@isTest
public class TestCarePlanStepCreation 
{ 
	public static testmethod void TestCreation ()
	{
	    Contact youngPerson = new Contact (LastName = 'Kelly');
        insert youngPerson;
        
        Care_Plan_Objective__c careplan = new Care_Plan_Objective__c (Area__c='Health', Name='Improve welbeing', Client__c=youngPerson.id);
        insert careplan;
 
		Care_Plan_Step__c step = new Care_plan_step__c ();

 		Test.setCurrentPageReference(new PageReference('Page.CarePlanStepCreation')); 
		System.currentPageReference().getParameters().put('PARENT', careplan.id);

    	ApexPages.StandardController programController = new ApexPages.StandardController(step);
    	CarePlanStepCreation cpsc = new CarePlanStepCreation (programController);
		cpsc.save();
		
		list <Care_plan_step__c> createdSteps = [select ID from Care_plan_step__c where Care_Plan_Objective__c = :careplan.id];
		system.assertEquals (1, createdSteps.size());
	}
}