src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Initials__c</fullName>
        <formula>LEFT (FirstName,1) &amp; LEFT (LastName, 1)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Initials</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Clients</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/NDTRS_Form_2016__c.object
<CustomObject>
    <description>Record of Treatment - Section D, E, F, G and H of NDTRS 2016 form</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>NDTRS_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>X35_Date_of_Final_Discharge_or_transfer__c</fullName>
        <description>Date of final discharge or transfer</description>
        <inlineHelpText>Date of final discharge or transfer</inlineHelpText>
        <label>35 Date of Final Discharge or transfer</label>
        <type>Date</type>
    </fields>
    <label>NDTRS LINK Form</label>
    <nameField>
        <label>NDTRS LINK Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NDTRS LINK Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CheckForOpenNDTRSLinkFormsController.cls
/*
	Author: Eamon Kelly, Enclude
	Purpose: A client can only have one open NDTRS form
	Called from: NewNDTRSLinkForm which overrides the new NDTRS_Form_2016__c standard page
*/
public with sharing class CheckForOpenNDTRSLinkFormsController {
    public list<NDTRS_Form_2016__c>openForms {get;set;}
    
    public CheckForOpenNDTRSLinkFormsController(ApexPages.StandardController controller) 
    {
    }
    
    public pageReference countOpenForms ()
    {
        Schema.DescribeSObjectResult dsr = NDTRS_Form_2016__c.SObjectType.getDescribe();
        try
        {
            // find the ID from the parameters
            ID contactID = null;
            map<String,String> parametersMap = ApexPages.currentPage().getParameters();
            for (String oneKey: parametersMap.keySet())
            {
                if (oneKey.contains('_lkid'))
                {
                    contactID = (ID)parametersMap.get(oneKey);
                    break;
                }
            }
            openForms = [SELECT Id, Name FROM NDTRS_Form_2016__c where X35_Date_of_Final_Discharge_or_transfer__c = null and Contact__c = :contactID Limit 100];
            if (openForms.size() > 0)
            {
                String msg = Label.NDTRS_Link_Form_Open_Msg;
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, msg);
                ApexPages.addMessage(myMsg);
                return null;
            }       
            else
            {
                Contact client = [select Name, Initials__c from Contact where ID = :contactID limit 1];
                String nameTemplate = AppConfigSupport.HRBFormNameTemplate;
                
                String tempName = nameTemplate.replace('$NAME$', client.Name).replace('$DATE$', '').replace('$INITIALS$', client.Initials__c);
                
                PageReference newNDTRSLinkFormPage = new PageReference('/' + dsr.getKeyPrefix() + '/e?nooverride=1&Name=' + tempName);
                newNDTRSLinkFormPage.setRedirect(true);
                newNDTRSLinkFormPage.getParameters().putall(parametersMap);
                String url = newNDTRSLinkFormPage.getUrl();
                url = url.remove('&save_new=1');
                return new PageReference (url);
             }
        }
        catch (Exception e)
        {
            // page not called from the contact page, so just show the normal new Form page
            PageReference newNDTRSLinkFormPage = new PageReference('/' + dsr.getKeyPrefix() + '/e?nooverride=1');
            newNDTRSLinkFormPage.setRedirect(true);
            return newNDTRSLinkFormPage;
        }       
    }
}