src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Clients</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Needle_Exchange__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Client</value>
            </filterItems>
            <infoMessage>Showing only clients</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>NSP Interventions</relationshipLabel>
        <relationshipName>Needle_Syringe_Exchange</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Exchange__c</fullName>
        <label>Date of intervention</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <picklist>
            <picklistValues>
                <fullName>Cavan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dublin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Laois</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Longford</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Louth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meath</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monaghan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Offaly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Westmeath</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Limerick</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>X1ml_Diabetic_Dispensed__c</fullName>
        <label>1ml Diabetic Dispensed</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X1ml_Filter_Dispensed__c</fullName>
        <label>1ml Filter Dispensed</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>NSP Intervention</label>
    <nameField>
        <displayFormat>NSE-{000}-{MM}{YY}</displayFormat>
        <label>NSP Intervention</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NSP Interventions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Needle_Syringe_Stock__c.object
<CustomObject>
    <fields>
        <fullName>X1ml_Diabetic__c</fullName>
        <label>1ml Diabetic</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X1ml_Filter__c</fullName>
        <label>1ml Filter</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>NSP Stock</label>
    <nameField>
        <label>Stock Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NSP Stock</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestTriggers.cls
@isTest
private class TestTriggers 
{
    static testMethod void updateStockTest() 
    {
        Needle_Syringe_Stock__c testStock = new Needle_Syringe_Stock__c (Name='Dublin', X1ml_Diabetic__c=100, X1ml_Filter__c=100);
        insert testStock;
        
        ID clientRecordTypeID = [select ID from RecordType where Name='Client'].id;
        Contact client = new Contact (LastName = 'Fred', Gender__c = 'Male', RecordTypeID=clientRecordTypeID);
        insert client;
 
        Needle_Exchange__c intervention1 = new Needle_Exchange__c (Client__c=client.id, Date_Exchange__c = system.today(), Location__c='Dublin', X1ml_Filter_Dispensed__c=5);
        insert intervention1;

        testStock = [select id, X1ml_Filter__c from Needle_Syringe_Stock__c where id=:testStock.id];
        System.assertEquals(95, testStock.X1ml_Filter__c);
                
        intervention1.X1ml_Diabetic_Dispensed__c = 10;
        update intervention1;
        
        testStock = [select id, X1ml_Filter__c, X1ml_Diabetic__c from Needle_Syringe_Stock__c where id=:testStock.id];
        
        System.assertEquals(95, testStock.X1ml_Filter__c);
        System.assertEquals(90, testStock.X1ml_Diabetic__c);
    }
 }