src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>X10b_Ethnic_Background__c</fullName>
        <label>10b. Ethnic Background</label>
        <picklist>
            <picklistValues>
                <fullName>1. White Irish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. White Irish Traveller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Any other white background</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Black African background</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Any other black background</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Chinese background</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7. Any other Asian background</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8. Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9. Do not wish to answer this question</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>X11_Employement_Status__c</fullName>
        <label>11. Employement Status</label>
        <picklist>
            <picklistValues>
                <fullName>1. In paid employment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. Unemployed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Fas/training course</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Housewife/husband</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Retired/unable to work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8. Other (specify)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9. Not Known</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>X11_Employement_Status_other__c</fullName>
        <inlineHelpText>If 8. Other above please specify</inlineHelpText>
        <label>11. Employement Status other</label>
        <length>90</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X12a_Age_left_primary_school__c</fullName>
        <description>Year left school (not third level)
01. Never went to school
88. Still at school
99. Not known</description>
        <inlineHelpText>Year left school (not third level)
01. Never went to school
88. Still at school
99. Not known</inlineHelpText>
        <label>12a. Age left primary/secondary school</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X12b_Education_highest_level__c</fullName>
        <label>12b. Education highest level</label>
        <picklist>
            <picklistValues>
                <fullName>0. Primary Level incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1. Primary level</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. Junior cert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Leaving Cert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Third Level</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Never went to school</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Special needs education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8. Still in education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9. Not known</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>X4_Gender__c</fullName>
        <inlineHelpText>1. Male
2. Female</inlineHelpText>
        <label>4. Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Male child</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female child</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>X7a_Living_with_whom__c</fullName>
        <label>7a. Living with whom?</label>
        <picklist>
            <picklistValues>
                <fullName>1. Alone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. Parents/family</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Friends</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Partner (alone)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Partner &amp; Child(ren)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Alone with child(ren)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7. Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8. Foster Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9. Not known</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>X7b_Livin_Where__c</fullName>
        <label>7b. Living Where?</label>
        <picklist>
            <picklistValues>
                <fullName>1. Stable Accommodation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. Institution(prison/residential care/halfway house)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Homeless</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Other unstable accommodation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9. Not Known</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Clients</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MigrateClientController.cls
/*
	Author: Eamon Kelly, Enclude
	Purpose: Move values in the client from HRB pre 2016 to NDTRS 2016 value
*/
public with sharing class MigrateClientController {
	Contact client;
    public MigrateClientController(ApexPages.StandardController controller) {
        client = (Contact)controller.getRecord();
    }
    public void DoMigration (){
    	if (client.X4_Gender__c == 'Male'){
    		client.X4_Gender__c = '1. Male';
    	} else if (client.X4_Gender__c == 'Female'){
    		client.X4_Gender__c = '2. Female';
    	}
		client.X5_Living_with_whom__c = client.X7a_Living_with_whom__c;
		if (client.X7b_Livin_Where__c == '2. Institution(prison/residential care/halfway house)'){
			client.X7_Living_Where__c = '1. Stable Accommodation';
		} else {
			client.X7_Living_Where__c = client.X7b_Livin_Where__c;
		}
		if (client.X12b_Education_highest_level__c == '6. Special needs education' || client.X12b_Education_highest_level__c == '8. Still in education' || client.X12b_Education_highest_level__c == null || client.X12b_Education_highest_level__c == ''){
			client.X9a_Education_highest_level__c = '9. Not known';
		} else {
			client.X9a_Education_highest_level__c = client.X12b_Education_highest_level__c;
		}
		client.X9b_Age_left_primary_school__c = client.X12a_Age_left_primary_school__c;
		if (client.X11_Employement_Status__c == '3. Fas/training course'){
			client.X10_Employement_Status__c = '3. Training course';
		} else {
			client.X10_Employement_Status__c = client.X11_Employement_Status__c; 
		}
		client.X10_8_Specify_other_employment_status__c = client.X11_Employement_Status_other__c;
		client.X11b_Ethnic_cultural_background__c = client.X10b_Ethnic_Background__c;

    	List<Schema.FieldSetMember> fieldsToZero = SObjectType.Contact.FieldSets.Fields_to_initialise_during_migration.getFields();
		for(Schema.FieldSetMember f : fieldsToZero) {
            client.put(f.getFieldPath(),0);
	    }
    }
    public pageReference ConfirmChanges (){
    	ID ndtrsClientID = [select id from RecordType where sObjectType='Contact' and DeveloperName='NDTRS_Client'].id;
    	client.RecordTypeID = ndtrsClientID; 
	    update client;
		return new PageReference ('/' + client.id);    	
    }
}