src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Initials__c</fullName>
        <formula>LEFT (FirstName,1) &amp; LEFT (LastName, 1)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Initials</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Clients</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/HRB_Form__c.object
<CustomObject>
    <description>Record of Treatment - Section D, E, F, G and H of HRB Form</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>HRB Forms</relationshipLabel>
        <relationshipName>HRB_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>X37_Date_of_Final_Discharge__c</fullName>
        <description>Date of final discharge or transfer</description>
        <inlineHelpText>Date of final discharge or transfer</inlineHelpText>
        <label>37 Date of Final Discharge</label>
        <type>Date</type>
    </fields>
    <label>HRB Form</label>
    <nameField>
        <label>HRB Form Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HRB Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CheckForOpenHRBFormsController.cls
public with sharing class CheckForOpenHRBFormsController 
{
	public list<HRB_Form__c>openForms {get;set;}
	
	public CheckForOpenHRBFormsController(ApexPages.StandardController controller) 
	{
	}
	
	public pageReference countOpenHRBForms ()
	{
		Schema.DescribeSObjectResult dsr = HRB_Form__c.SObjectType.getDescribe();
		try
		{
			// find the ID from the parameters
			ID contactID = null;
			map<String,String> parametersMap = ApexPages.currentPage().getParameters();
			for (String oneKey: parametersMap.keySet())
			{
				if (oneKey.contains('_lkid'))
				{
					contactID = (ID)parametersMap.get(oneKey);
					break;
				}
			}
			openForms = [SELECT Id, Name FROM HRB_Form__c where X37_Date_of_Final_Discharge__c = null and Contact__c = :contactID Limit 100];
			if (openForms.size() > 0)
			{
	    		String msg = Label.HRB_Form_Open_Msg;
	    		ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, msg);
	            ApexPages.addMessage(myMsg);
	            return null;
			}		
			else
			{
				Contact client = [select Name, Initials__c from Contact where ID = :contactID limit 1];
				String nameTemplate = AppConfigSupport.HRBFormNameTemplate;
				
				String tempName = nameTemplate.replace('$NAME$', client.Name).replace('$DATE$', '').replace('$INITIALS$', client.Initials__c);
				
				PageReference newHRBFormPage = new PageReference('/' + dsr.getKeyPrefix() + '/e?nooverride=1&Name=' + tempName);
				newHRBFormPage.setRedirect(true);
				newHRBFormPage.getParameters().putall(parametersMap);
				return newHRBFormPage;
			}
		}
		catch (Exception e)
		{
			// page not called from the contact page, so just show the normal new HRB Form page
			PageReference newHRBFormPage = new PageReference('/' + dsr.getKeyPrefix() + '/e?nooverride=1');
			newHRBFormPage.setRedirect(true);
			return newHRBFormPage;
		}		
	}
}