src/objects/HRB_Form__c.object
<CustomObject>
    <description>Record of Treatment - Section D, E, F, G and H of HRB Form</description>
    <fields>
        <fullName>Contact_Record_Valid__c</fullName>
        <formula>Contact__r.Record_Valid__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Record Valid</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>HRB Forms</relationshipLabel>
        <relationshipName>HRB_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Drug_Validation__c</fullName>
        <formula>IF(X14_Main_Reason_for_Referral_Drug__r.Tableyear2012__c = FALSE,&quot;Invalid Drug Q14&quot;, 

IF( OR( X14_Main_Reason_for_Referral_Drug__r.DrugCode__c = &quot;994&quot;, 

TEXT(X17a_Assessment_outcome__c) = &quot;2. Unsuitable for treatment&quot;, 

TEXT( X17b_Assessment_criterion_fulfilled__c ) = &quot;2. No&quot;, 

TEXT( X18a_Clients_treatment_status__c ) = &quot;3. Transferred to another site&quot;, 

TEXT( X18a_Clients_treatment_status__c ) = &quot;4. Psychiatric assessment only&quot;, 

TEXT( X19_Accepted_place_at_this_centre__c ) = &quot;2. No&quot;), 

&quot;HRB OK&quot;, 

IF( AND(OR(X25a_Main_substance__r.drugtype__c = &quot;2&quot;, X26a_Substance_2__r.drugtype__c = &quot;2&quot;, X27a_Substance_3__r.drugtype__c = &quot;2&quot;, X28a_Substance_4__r.drugtype__c = &quot;2&quot;), X24b_Specify_first_drug_used__r.DrugCode__c = &quot;998&quot;) , &quot;Q24b Invalid&quot;, 

IF( AND(OR(X25a_Main_substance__r.drugtype__c = &quot;3&quot;, X26a_Substance_2__r.drugtype__c = &quot;3&quot;, X27a_Substance_3__r.drugtype__c = &quot;3&quot;, X28a_Substance_4__r.drugtype__c = &quot;3&quot;), X24b_Specify_first_drug_used__r.DrugCode__c = &quot;998&quot;) , &quot;Q24b Invalid&quot;, 

IF( AND(OR(X25a_Main_substance__r.drugtype__c = &quot;2&quot;, X26a_Substance_2__r.drugtype__c = &quot;2&quot;, X27a_Substance_3__r.drugtype__c = &quot;2&quot;, X28a_Substance_4__r.drugtype__c = &quot;2&quot;), X24a_Age_first_use_any_drug__c = 88) , &quot;Q24a Invalid&quot;, 

IF( AND(OR(X25a_Main_substance__r.drugtype__c = &quot;3&quot;, X26a_Substance_2__r.drugtype__c = &quot;3&quot;, X27a_Substance_3__r.drugtype__c = &quot;3&quot;, X28a_Substance_4__r.drugtype__c = &quot;3&quot;), X24a_Age_first_use_any_drug__c = 88) , &quot;Q24a Invalid&quot;, 

IF( AND(X24a_Age_first_use_any_drug__c &lt;&gt; 88, NOT(ISBLANK( X25a_Main_substance__c )), X25a_Main_substance__r.drugtype__c &lt;&gt; &quot;1&quot;, X24a_Age_first_use_any_drug__c &gt; X25d_Age_at_1st_use__c ), &quot;Q24a Invalid should be &lt;= Q25d&quot;, 

IF( AND(X24a_Age_first_use_any_drug__c &lt;&gt; 88, NOT(ISBLANK( X26a_Substance_2__c )), X26a_Substance_2__r.drugtype__c &lt;&gt; &quot;1&quot;, X24a_Age_first_use_any_drug__c &gt; X26d_Age_of_1st_use__c ), &quot;Q24a Invalid should be &lt;= Q26d&quot;, 

IF( AND(X24a_Age_first_use_any_drug__c &lt;&gt; 88, NOT(ISBLANK( X27a_Substance_3__c )), X27a_Substance_3__r.drugtype__c &lt;&gt; &quot;1&quot;, X24a_Age_first_use_any_drug__c &gt; X27d_Age_of_1st_use__c ), &quot;Q24a Invalid should be &lt;= Q27d&quot;, 

IF( AND(X24a_Age_first_use_any_drug__c &lt;&gt; 88, NOT(ISBLANK( X28a_Substance_4__c )), X28a_Substance_4__r.drugtype__c &lt;&gt; &quot;1&quot;, X24a_Age_first_use_any_drug__c &gt; X28d_Age_of_1st_use__c ), &quot;Q24a Invalid should be &lt;= Q28d&quot;, 

IF( AND(X24a_Age_first_use_any_drug__c &lt;&gt; 88, X29c_Age_first_injected__c &lt;&gt; 0, X24a_Age_first_use_any_drug__c &gt; X29c_Age_first_injected__c), &quot;Q24a Invalid should be &lt;= Q29c&quot;, 

IF(AND( TEXT(X29b_Ever_injected__c ) = &quot;9. Not Known&quot;, X29c_Age_first_injected__c = 88), &quot;Q29c Invalid&quot;, 

&quot;HRB OK&quot;))))))))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Drug Validation</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExitDate__c</fullName>
        <formula>DATEVALUE(

IF( OR( X14_Main_Reason_for_Referral_Drug__r.DrugCode__c = &quot;994&quot;,

TEXT(X17a_Assessment_outcome__c) = &quot;2. Unsuitable for treatment&quot;,

TEXT( X17b_Assessment_criterion_fulfilled__c ) = &quot;2. No&quot;,

TEXT( X18a_Clients_treatment_status__c ) = &quot;3. Transferred to another site&quot;,

TEXT( X18a_Clients_treatment_status__c ) =&quot;4. Psychiatric assessment only&quot;,

TEXT( X19_Accepted_place_at_this_centre__c ) = &quot;2. No&quot;),

&quot;&quot;, 

TEXT(  X37_Date_of_Final_Discharge__c )))</formula>
        <label>ExitDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>HRB_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This will be populated automatically when you click the button in the HRB Report</inlineHelpText>
        <label>HRB Report</label>
        <referenceTo>HRB_Report__c</referenceTo>
        <relationshipLabel>HRB Forms</relationshipLabel>
        <relationshipName>HRB_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Main_Intervention_Valid__c</fullName>
        <formula>IF(X14_Main_Reason_for_Referral_Drug__r.DrugCode__c = &quot;994&quot;, &quot;HRB OK&quot;, 

IF(AND(TEXT( X15b_If_client_referred__c ) = &quot;8. Other (specify)&quot;, ISBLANK( X15b8_Other_specify__c )), &quot;Q15b8 Other specify Incomplete&quot;, 

IF(OR(TEXT(X17a_Assessment_outcome__c) = &quot;2. Unsuitable for treatment&quot;, 

TEXT( X17b_Assessment_criterion_fulfilled__c ) = &quot;2. No&quot;, 

TEXT( X18a_Clients_treatment_status__c ) = &quot;3. Transferred to another site&quot;, 

TEXT( X18a_Clients_treatment_status__c ) = &quot;4. Psychiatric assessment only&quot;, 

TEXT( X19_Accepted_place_at_this_centre__c ) = &quot;2. No&quot;), 

&quot;HRB OK&quot;, 

IF(ISBLANK( TEXT(X33a_Main_Intervention__c )), &quot;Q33a Invalid Main Intervention&quot;, 

IF(AND(ISBLANK(X33b1_Date_Commenced__c), TEXT(X33a_Main_Intervention__c ) = &quot;1. Brief intervention&quot;), &quot;Q33a Main Intervention Invalid&quot;, 

IF(AND(ISBLANK(X33b12_Date_Commenced__c), TEXT(X33a_Main_Intervention__c ) = &quot;12. Medication free therapy psychosocial therapy other etc&quot;),&quot;Q33a Main Intervention Invalid&quot;, 

IF(AND(ISBLANK(X33b13_Date_Commenced__c ), TEXT(X33a_Main_Intervention__c ) = &quot;13. Psychiatric therapy&quot;), &quot;Q33a Main Intervention Invalid&quot;, 

IF(AND(ISBLANK(X33b14_Date_Commenced__c ), TEXT(X33a_Main_Intervention__c ) = &quot;14. Individual counselling&quot;), &quot;Q33a Main Intervention Invalid&quot;, 

IF(AND(ISBLANK( X33b15_Date_Commenced__c), TEXT(X33a_Main_Intervention__c ) = &quot;15. Group counselling&quot;), &quot;Q33a Main Intervention Invalid&quot;, 

IF(AND(ISBLANK( X33b16_Date_Commenced__c), TEXT(X33a_Main_Intervention__c ) = &quot;16. Social and/or occupational reintegration&quot;), &quot;Q33a Main Intervention Invalid&quot;, 

IF(AND(ISBLANK(X33b17_Date_Commenced__c ), TEXT(X33a_Main_Intervention__c ) = &quot;17. Family Therapy&quot;), &quot;Q33a Main Intervention Invalid&quot;, 

IF(AND(ISBLANK(X33b18_Date_Commenced__c), TEXT(X33a_Main_Intervention__c ) = &quot;18. Brief intervention: individual education/awareness programme&quot;), &quot;Q33a Main Intervention Invalid&quot;, 

IF(AND(ISBLANK( X33b19_Date_Commenced__c ), TEXT(X33a_Main_Intervention__c ) = &quot;19. Group education/awareness programme&quot;), &quot;Q33a Main Intervention Invalid&quot;, 

IF(AND(ISBLANK( X33b20_Date_Commenced__c ), TEXT(X33a_Main_Intervention__c ) = &quot;20. Aftercare&quot;), &quot;Q33a Main Intervention Invalid&quot;, 

IF(AND(ISBLANK(X33b21_Date_Commenced__c ), TEXT(X33a_Main_Intervention__c ) = &quot;21. Complementary therapies&quot;), &quot;Q33a Main Intervention Invalid&quot;, 

IF(AND(ISBLANK(X33b23_Date_Commenced__c ), TEXT(X33a_Main_Intervention__c ) = &quot;23. Strengthening family programme&quot;), &quot;Q33a Main Intervention Invalid&quot;, 

&quot;HRB OK&quot; ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Main Intervention Valid</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Treatment_Type_Check__c</fullName>
        <formula>IF( OR( X14_Main_Reason_for_Referral_Drug__r.DrugCode__c = &quot;994&quot;,

TEXT(X17a_Assessment_outcome__c) = &quot;2. Unsuitable for treatment&quot;,

TEXT( X17b_Assessment_criterion_fulfilled__c ) = &quot;2. No&quot;,

TEXT( X18a_Clients_treatment_status__c ) = &quot;3. Transferred to another site&quot;,

TEXT( X18a_Clients_treatment_status__c ) = &quot;4. Psychiatric assessment only&quot;,

TEXT(X19_Accepted_place_at_this_centre__c ) = &quot;2. No&quot;),

&quot;HRB OK&quot;,

IF(AND(TEXT(X14_Main_Reason_for_referral__c ) = &quot;1. Alcohol&quot;, ISBLANK(TEXT(X22_Ever_previously_treated_alc_drug__c))), &quot;Invalid Q22&quot;,

IF(AND(TEXT(X14_Main_Reason_for_referral__c) = &quot;2. Illicit drug&quot;, ISBLANK(TEXT(X22_Ever_previously_treated_re_drug__c))), &quot;Invalid Q22&quot;,

IF(AND(TEXT(X14_Main_Reason_for_referral__c) = &quot;3. Licit drug&quot;, ISBLANK(TEXT(X22_Ever_previously_treated_re_drug__c ))), &quot;Invalid Q22&quot;,

IF(AND( X20_Number_times_started_this_year__c &gt; 0, ISBLANK(TEXT(X23_Type_of_contact_with_this_centre__c ))), &quot;Invalid Q23&quot;,

IF(ISBLANK(X21a_Date_This_treatment_started__c ), &quot;Q21a Invalid date this treatment started&quot;,

IF( X21a_Date_This_treatment_started__c &lt; X16_Date_of_Assessment__c , &quot;Q21a Invalid can&apos;t be before Q16 Date of Assessment&quot;,

&quot;HRB OK&quot;) ) ) ) ) ) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Validation on type of contact with this centre</inlineHelpText>
        <label>Treatment Type Check</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X16_Date_of_Assessment__c</fullName>
        <label>16 Date of Assessment</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X21a_Date_This_treatment_started__c</fullName>
        <label>21a Date This treatment started</label>
        <type>Date</type>
    </fields>
    <label>HRB Form</label>
    <nameField>
        <label>HRB Form Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HRB Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/HRB_Report__c.object
<CustomObject>
    <description>Used to select the range and type of HRB Report</description>
    <fields>
        <fullName>Period__c</fullName>
        <inlineHelpText>Select the period for the report</inlineHelpText>
        <label>Period</label>
        <picklist>
            <picklistValues>
                <fullName>Complete Year</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Quarter 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarter 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarter 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarter 4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type_of_report__c</fullName>
        <label>Type of report</label>
        <picklist>
            <picklistValues>
                <fullName>Clients who entered during the report period</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Only clients who entered before the reporting period and exited during the report period</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <inlineHelpText>Enter a four digit year (e.g. 2011)</inlineHelpText>
        <label>Year</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>HRB Report</label>
    <nameField>
        <displayFormat>HRB-{000}</displayFormat>
        <label>HRB Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HRB Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AddTreatmentToReport.cls
/*
	Author: Eamon Kelly, Enclude
	Purpose: Test the treatments to make sure they pass the validation rules by adding a pointer to the HRB Report object
	Called from: AddTreatmentToReport page which is called from a button on the HRB Report page
	Tested in: TestAddTreatmentToReport

	EK 22/09/2015 To avoid XSRF issues, the list of treatments to be added is displayed first and then added to the report when a button is clicked
	EK 29/01/2016 Changing to update the treatments all in one go (needed for end of year)
	EK 9/11/2016 changing to use Q21a Date this treatment started instead of Q16 Date of assessment as the criteria to select the forms
*/
public with sharing class AddTreatmentToReport 
{
	public class TreatmentMessages
	{
		public ID treatmentID {get;set;}
		public String errorMsg {get;set;}
		public TreatmentMessages (HRB_Form__c treat, String msg)
		{
			treatmentID = treat.Id;
			errorMsg = msg;
		}	
	}
	
    public HRB_Form__c[] TreatmentsWithClientsList {get;Set;} // these are the HRB forms
    public HRB_Report__c reportParams {get;set;} // this will be the object with the date range (last year, q1 etc)
	public list<TreatmentMessages> passed {get;set;}
	public list<TreatmentMessages> failed {get; set;}
	public Integer TreatmentsListSize {get;set;}
	public Integer TreatmentsToProcess {get;set;}
	public Boolean showResults {get; Set;}
	
	public AddTreatmentToReport (ApexPages.StandardController controller)
	{
		showResults = false;
		passed = new list<TreatmentMessages>();
		failed = new list<TreatmentMessages>();
		this.reportParams = (HRB_Report__c)controller.getRecord();
	}
	
	public void Initialise ()
	{
		reportParams = [select id, Name, Period__c, Year__c, Type_of_report__c from HRB_Report__c where id = :reportParams.id];
        Integer year = reportParams.Year__c.intValue();
        String startMonthDay = '-01-01';
        String endMonthDay = '-12-31';
        if (reportParams.Period__c == 'Quarter 1')
        {
            endMonthDay = '-03-31';
        }
        else if (reportParams.Period__c == 'Quarter 2')
        {
            startMonthDay = '-04-01';
            endMonthDay = '-06-30';
        }
        else if (reportParams.Period__c == 'Quarter 3')
        {
            startMonthDay = '-07-01';
            endMonthDay = '-09-30';
        }
        else if (reportParams.Period__c == 'Quarter 4')
        {
            startMonthDay = '-10-01';
        }
        String startReportPeriod = String.valueOf(year) + startMonthDay;
        String endReportPeriod = String.valueOf(year) + endMonthDay;
 
 		String queryString = 'select id, Name, Contact__c, X16_Date_of_Assessment__c, X21a_Date_This_treatment_started__c, HRB_Report__c, Contact_Record_Valid__c, Main_Intervention_Valid__c, Drug_Validation__c, Treatment_Type_Check__c from HRB_Form__c where HRB_Report__c != \'' + reportParams.Id + '\' and ';
 		
 		 if (reportParams.Type_of_report__c == 'Clients who entered during the report period') 
         {
            queryString += 'X21a_Date_This_treatment_started__c >= ' + startReportPeriod + ' and X21a_Date_This_treatment_started__c <= ' + endReportPeriod;
         }
         else
         {
            queryString += 'ExitDate__c >= ' + startReportPeriod + ' and ExitDate__c <= ' + endReportPeriod + ' and X21a_Date_This_treatment_started__c < ' + startReportPeriod;
         }
         
         TreatmentsWithClientsList = Database.query(queryString);
         TreatmentsListSize = TreatmentsWithClientsList.size();
         TreatmentsToProcess = math.min (TreatmentsListSize, Limits.getLimitDmlRows());
         if (TreatmentsToProcess < TreatmentsListSize)
         {
         	queryString += ' limit ' + TreatmentsToProcess;
         	TreatmentsWithClientsList = Database.query(queryString);
         }
         system.debug ('Number of possible treatments: ' + TreatmentsWithClientsList.size());
     }

	 public void ProcessTreatments ()
	 {
         list<HRB_Form__c> TreatmentsToUpdate = new list<HRB_Form__c>(); // these are the HRB forms
         for (HRB_Form__c oneTreatment: TreatmentsWithClientsList)
         {
         	system.debug ('Treatment limits rows: ' + Limits.getLimitDmlRows() + ' queries: ' + Limits.getLimitQueries());
			if (oneTreatment.Contact_Record_Valid__c != 'HRB OK') 
			{
				failed.add (new TreatmentMessages(oneTreatment, oneTreatment.name + ' Failed because client record error: ' + oneTreatment.Contact_Record_Valid__c));
			}
			else if (oneTreatment.Main_Intervention_Valid__c != 'HRB OK')
			{
				failed.add (new TreatmentMessages(oneTreatment, oneTreatment.name + ' Failed because: ' + oneTreatment.Main_Intervention_Valid__c));
			}
			else if (oneTreatment.Treatment_Type_Check__c != 'HRB OK')
			{
				failed.add (new TreatmentMessages(oneTreatment, oneTreatment.name + ' Failed because: ' + oneTreatment.Main_Intervention_Valid__c));
			}
			else if (oneTreatment.Drug_Validation__c != 'HRB OK')
			{
				failed.add (new TreatmentMessages(oneTreatment, oneTreatment.name + ' Failed because: ' + oneTreatment.Main_Intervention_Valid__c));
			}
			else
			{
				oneTreatment.HRB_Report__c = reportParams.id;
				try
				{
	 				TreatmentsToUpdate.add (oneTreatment);
		            passed.add (new TreatmentMessages(oneTreatment, oneTreatment.name + ' Attached'));
		            system.debug ('Treatment added ' + oneTreatment.name);
				}
			    catch (Exception e)
			    {
			    	system.debug ('Treatment failed ' + e.getMessage());
			    	string errorMsg = e.getMessage().subString (e.getMessage().indexOf ('first error:'));
			       	failed.add (new TreatmentMessages(oneTreatment, oneTreatment.name + ' Failed ' + errorMsg));
			    }
			}
         }
         if (TreatmentsToUpdate.size() > 0) update TreatmentsToUpdate;
		 showResults = true;
	}
}