src/objects/HRB_Form__c.object
<CustomObject>
    <description>Record of Treatment - Section D, E, F, G and H of HRB Form</description>
    <fields>
        <fullName>X21a_Date_This_treatment_started__c</fullName>
        <label>21a Date This treatment started</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33b12_Date_Commenced__c</fullName>
        <description>Date commenced
each type of treatment intervention</description>
        <inlineHelpText>Date commenced
each type of treatment intervention</inlineHelpText>
        <label>33b12 Date Commenced</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33b1_Date_Commenced__c</fullName>
        <description>Date commenced
each type of treatment intervention</description>
        <inlineHelpText>Date commenced
each type of treatment intervention</inlineHelpText>
        <label>33b1 Date Commenced</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33c12_Date_Completed__c</fullName>
        <description>Medication-free therapy - Date Completed</description>
        <inlineHelpText>Medication-free therapy - Date Completed</inlineHelpText>
        <label>33c12 Date Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33c13_Date_Completed__c</fullName>
        <label>33c13 Date Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33c14_Date_Completed__c</fullName>
        <description>Individual Counselling - Date Completed</description>
        <inlineHelpText>Individual Counselling - Date Completed</inlineHelpText>
        <label>33c14 Date Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33c15_Date_Completed__c</fullName>
        <description>Group Counselling - Date Comleted</description>
        <inlineHelpText>Group Counselling - Date Comleted</inlineHelpText>
        <label>33c15 Date Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33c16_Date_Completed__c</fullName>
        <label>33c16 Date Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33c17_Date_Completed__c</fullName>
        <description>Family Therapy - Date Completed</description>
        <inlineHelpText>Family Therapy - Date Completed</inlineHelpText>
        <label>33c17 Date Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33c18_Date_Completed__c</fullName>
        <label>33c18 Date Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33c19_Date_Completed__c</fullName>
        <label>33c19 Date Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33c1_Date_Completed__c</fullName>
        <description>Brief Intervention - Date Completed</description>
        <inlineHelpText>Brief Intervention - Date Completed</inlineHelpText>
        <label>33c1 Date Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33c20_Date_Completed__c</fullName>
        <description>Aftercare - Date Completed</description>
        <inlineHelpText>Aftercare - Date Completed</inlineHelpText>
        <label>33c20 Date Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33c21_Date_Completed__c</fullName>
        <description>Complimentary Therapies - Date Completed</description>
        <inlineHelpText>Complimentary Therapies - Date Completed</inlineHelpText>
        <label>33c21 Date Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33c23_Date_Completed__c</fullName>
        <description>Family consultations - Date Completed</description>
        <inlineHelpText>Family consultations - Date Completed</inlineHelpText>
        <label>33c23 Date Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33c28_Date_Completed__c</fullName>
        <inlineHelpText>Facilitated detox - Date Completed</inlineHelpText>
        <label>33c28 Date Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X33d12_Number_of_Sessions__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Medication-free therapy - Number of Sessions</description>
        <inlineHelpText>Medication-free therapy - Number of Sessions</inlineHelpText>
        <label>33d12 Number of Sessions</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X33d13_Number_of_Sessions__c</fullName>
        <defaultValue>0</defaultValue>
        <label>33d13 Number of Sessions</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X33d14_Number_of_Sessions__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Individual counselling - Number of Sessions</description>
        <inlineHelpText>Individual counselling - Number of Sessions</inlineHelpText>
        <label>33d14 Number of Sessions</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X33d15_Number_of_Sessions__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Group Counselling - Number of Sessions</description>
        <inlineHelpText>Group Counselling - Number of Sessions</inlineHelpText>
        <label>33d15 Number of Sessions</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X33d16_Number_of_Sessions__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Social and/or occupational reintegration - Number of Sessions</inlineHelpText>
        <label>33d16 Number of Sessions</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X33d17_Number_of_Sesions__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Family Therapy - Number of Sessions</description>
        <inlineHelpText>Family Therapy - Number of Sessions</inlineHelpText>
        <label>33d17 Number of Sessions</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X33d18_Number_of_Sessions__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Brief intervention: individual education/awareness programme - Number of Sessions</inlineHelpText>
        <label>33d18 Number of Sessions</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X33d19_Number_of_Sessions__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Group education/awareness programme - Number of Sessions</inlineHelpText>
        <label>33d19 Number of Sessions</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X33d1_Number_of_Sessions__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Brief Intervention - Number of Sessions</description>
        <inlineHelpText>Brief Intervention - Number of Sessions</inlineHelpText>
        <label>33d1 Number of Sessions</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X33d20_Number_of_Sessions__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Aftercare - Number of Sessions</description>
        <inlineHelpText>Aftercare - Number of Sessions</inlineHelpText>
        <label>33d20 Number of Sessions</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X33d21_Number_of_Sessions__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Complimentary Therapies - Number of Sessions</description>
        <inlineHelpText>Complimentary Therapies - Number of Sessions</inlineHelpText>
        <label>33d21 Number of Sessions</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X33d23_Number_of_Sessions__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Strengthening family programme - Number of Sessions</inlineHelpText>
        <label>33d23 Number of Sessions</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X33d28_Number_of_Sessions__c</fullName>
        <inlineHelpText>Facilitated detox - Number of sessions provided</inlineHelpText>
        <label>33d28 Number of Sessions</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X37_Date_of_Final_Discharge__c</fullName>
        <description>Date of final discharge or transfer</description>
        <inlineHelpText>Date of final discharge or transfer</inlineHelpText>
        <label>37 Date of Final Discharge</label>
        <type>Date</type>
    </fields>
    <label>HRB Form</label>
    <nameField>
        <label>HRB Form Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HRB Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestHRBFormRules3.cls
/*
	Author: Pedro Gonzalez, Enclude
	Purpose: More tests for the HRBReportController
*/
// Continuation of TestHRBForm
@isTest
private class TestHRBFormRules3 {

    static testMethod void TestEnsure_That_Q331c_and_Q331d_Are_Blank ()
    {
     	HRB_Form__c testTreatment = TestHRBFormRules2.TestQ25_to_Q28_Substances_are_all_different();
     	testTreatment.X37_Date_of_Final_Discharge__c = null;
     	testTreatment.X33b1_Date_Commenced__c = testTreatment.X21a_Date_This_treatment_started__c;
     	testTreatment.X33d1_Number_of_Sessions__c = 5;
     	testTreatment.X33b12_Date_Commenced__c = testTreatment.X21a_Date_This_treatment_started__c;
     	testTreatment.X33d12_Number_of_Sessions__c = 5;
     	update testTreatment;
     	
     	HRB_Form__c checkTreatment = [select X33c1_Date_Completed__c, X33d1_Number_of_Sessions__c from HRB_Form__c where id = :testTreatment.id];
     	system.assertEquals (0, checkTreatment.X33d1_Number_of_Sessions__c);
     	system.assertEquals (null, checkTreatment.X33c1_Date_Completed__c);
     	
     	
    }
    
    static testMethod void TestEnsure_That_Q3312c_and_Q3312d_Are_Blank ()
    {
     	HRB_Form__c testTreatment = TestHRBFormRules2.TestQ25_to_Q28_Substances_are_all_different();
     	testTreatment.X37_Date_of_Final_Discharge__c = null;
     	testTreatment.X33b1_Date_Commenced__c = testTreatment.X21a_Date_This_treatment_started__c;
     	testTreatment.X33d1_Number_of_Sessions__c = 5;
     	testTreatment.X33b12_Date_Commenced__c = testTreatment.X21a_Date_This_treatment_started__c;
     	testTreatment.X33d12_Number_of_Sessions__c = 5;
     	update testTreatment;
     	
     	HRB_Form__c checkTreatment = [select X33c12_Date_Completed__c, X33d12_Number_of_Sessions__c from HRB_Form__c where id = :testTreatment.id];
     	system.assertEquals (0, checkTreatment.X33d12_Number_of_Sessions__c);
     	system.assertEquals (null, checkTreatment.X33c12_Date_Completed__c);
     	
     	
    }
    
    static testMethod void TestEnsure_That_Q3313c_and_Q3313d_Are_Blank ()
    {
     	HRB_Form__c testTreatment = TestHRBFormRules2.TestQ25_to_Q28_Substances_are_all_different();
     	testTreatment.X37_Date_of_Final_Discharge__c = null;
     	testTreatment.X33b1_Date_Commenced__c = testTreatment.X21a_Date_This_treatment_started__c;
     	testTreatment.X33d1_Number_of_Sessions__c = 5;
     	testTreatment.X33b12_Date_Commenced__c = testTreatment.X21a_Date_This_treatment_started__c;
     	testTreatment.X33d12_Number_of_Sessions__c = 5;
     	update testTreatment;
     	
     	HRB_Form__c checkTreatment = [select X33c13_Date_Completed__c, X33d13_Number_of_Sessions__c from HRB_Form__c where id = :testTreatment.id];
     	system.assertEquals (0, checkTreatment.X33d13_Number_of_Sessions__c);
     	system.assertEquals (null, checkTreatment.X33c13_Date_Completed__c);
     	
     	
    }
    
    static testMethod void TestEnsure_That_Q3314c_and_Q3314d_Are_Blank ()
    {
     	HRB_Form__c testTreatment = TestHRBFormRules2.TestQ25_to_Q28_Substances_are_all_different();
     	testTreatment.X37_Date_of_Final_Discharge__c = null;
     	testTreatment.X33b1_Date_Commenced__c = testTreatment.X21a_Date_This_treatment_started__c;
     	testTreatment.X33d1_Number_of_Sessions__c = 5;
     	testTreatment.X33b12_Date_Commenced__c = testTreatment.X21a_Date_This_treatment_started__c;
     	testTreatment.X33d12_Number_of_Sessions__c = 5;
     	update testTreatment;
     	
     	HRB_Form__c checkTreatment = [select X33c14_Date_Completed__c, X33d14_Number_of_Sessions__c from HRB_Form__c where id = :testTreatment.id];
     	system.assertEquals (0, checkTreatment.X33d14_Number_of_Sessions__c);
     	system.assertEquals (null, checkTreatment.X33c14_Date_Completed__c);
     	
     	
    }
    
    static testMethod void TestEnsure_That_Q3315c_and_Q3315d_Are_Blank ()
    {
     	HRB_Form__c testTreatment = TestHRBFormRules2.TestQ25_to_Q28_Substances_are_all_different();
     	testTreatment.X37_Date_of_Final_Discharge__c = null;
     	testTreatment.X33b1_Date_Commenced__c = testTreatment.X21a_Date_This_treatment_started__c;
     	testTreatment.X33d1_Number_of_Sessions__c = 5;
     	testTreatment.X33b12_Date_Commenced__c = testTreatment.X21a_Date_This_treatment_started__c;
     	testTreatment.X33d12_Number_of_Sessions__c = 5;
     	update testTreatment;
     	
     	HRB_Form__c checkTreatment = [select X33c15_Date_Completed__c, X33d15_Number_of_Sessions__c from HRB_Form__c where id = :testTreatment.id];
     	system.assertEquals (0, checkTreatment.X33d15_Number_of_Sessions__c);
     	system.assertEquals (null, checkTreatment.X33c15_Date_Completed__c);
     	
     	
    }
    
    static testMethod void TestEnsure_That_Q3316c_and_Q3316d_Are_Blank ()
    {
     	HRB_Form__c testTreatment = TestHRBFormRules2.TestQ25_to_Q28_Substances_are_all_different();
     	testTreatment.X37_Date_of_Final_Discharge__c = null;
     	testTreatment.X33b1_Date_Commenced__c = testTreatment.X21a_Date_This_treatment_started__c;
     	testTreatment.X33d1_Number_of_Sessions__c = 5;
     	testTreatment.X33b12_Date_Commenced__c = testTreatment.X21a_Date_This_treatment_started__c;
     	testTreatment.X33d12_Number_of_Sessions__c = 5;
     	update testTreatment;
     	
     	HRB_Form__c checkTreatment = [select X33c16_Date_Completed__c, X33d16_Number_of_Sessions__c from HRB_Form__c where id = :testTreatment.id];
     	system.assertEquals (0, checkTreatment.X33d16_Number_of_Sessions__c);
     	system.assertEquals (null, checkTreatment.X33c16_Date_Completed__c);
     	
     	
    }
    
    static testMethod void TestEnsure_That_Q3317c_and_Q3317d_Are_Blank ()
    {
     	HRB_Form__c testTreatment = TestHRBFormRules2.TestQ25_to_Q28_Substances_are_all_different();
     	testTreatment.X37_Date_of_Final_Discharge__c = null;
     	testTreatment.X33b1_Date_Commenced__c = testTreatment.X21a_Date_This_treatment_started__c;
     	testTreatment.X33d1_Number_of_Sessions__c = 5;
     	testTreatment.X33b12_Date_Commenced__c = testTreatment.X21a_Date_This_treatment_started__c;
     	testTreatment.X33d12_Number_of_Sessions__c = 5;
     	update testTreatment;
     	
     	HRB_Form__c checkTreatment = [select X33c17_Date_Completed__c, X33d17_Number_of_Sesions__c from HRB_Form__c where id = :testTreatment.id];
     	system.assertEquals (0, checkTreatment.X33d17_Number_of_Sesions__c);
     	system.assertEquals (null, checkTreatment.X33c17_Date_Completed__c);
     	
     	
    }
    
    static testMethod void TestEnsure_That_Q3318c_and_Q3318d_Are_Blank ()
    {
     	HRB_Form__c testTreatment = TestHRBFormRules2.TestQ25_to_Q28_Substances_are_all_different();
     	testTreatment.X37_Date_of_Final_Discharge__c = null;
     	testTreatment.X33b1_Date_Commenced__c = testTreatment.X21a_Date_This_treatment_started__c;
     	testTreatment.X33d1_Number_of_Sessions__c = 5;
     	testTreatment.X33b12_Date_Commenced__c = testTreatment.X21a_Date_This_treatment_started__c;
     	testTreatment.X33d12_Number_of_Sessions__c = 5;
     	update testTreatment;
     	
     	HRB_Form__c checkTreatment = [select X33c18_Date_Completed__c, X33d18_Number_of_Sessions__c from HRB_Form__c where id = :testTreatment.id];
     	system.assertEquals (0, checkTreatment.X33d18_Number_of_Sessions__c);
     	system.assertEquals (null, checkTreatment.X33c18_Date_Completed__c);
     	
     	
    }
    
    static testMethod void TestEnsure_That_Q3319c_and_Q3319d_Are_Blank ()
    {
     	HRB_Form__c testTreatment = TestHRBFormRules2.TestQ25_to_Q28_Substances_are_all_different();
     	testTreatment.X37_Date_of_Final_Discharge__c = null;
     	testTreatment.X33b1_Date_Commenced__c = testTreatment.X21a_Date_This_treatment_started__c;
     	testTreatment.X33d1_Number_of_Sessions__c = 5;
     	testTreatment.X33b12_Date_Commenced__c = testTreatment.X21a_Date_This_treatment_started__c;
     	testTreatment.X33d12_Number_of_Sessions__c = 5;
     	update testTreatment;
     	
     	HRB_Form__c checkTreatment = [select X33c19_Date_Completed__c, X33d19_Number_of_Sessions__c from HRB_Form__c where id = :testTreatment.id];
     	system.assertEquals (0, checkTreatment.X33d19_Number_of_Sessions__c);
     	system.assertEquals (null, checkTreatment.X33c19_Date_Completed__c);
     	
     	
    }
    
    static testMethod void TestEnsure_That_Q3320c_and_Q3320d_Are_Blank ()
    {
     	HRB_Form__c testTreatment = TestHRBFormRules2.TestQ25_to_Q28_Substances_are_all_different();
     	testTreatment.X37_Date_of_Final_Discharge__c = null;
     	testTreatment.X33b1_Date_Commenced__c = testTreatment.X21a_Date_This_treatment_started__c;
     	testTreatment.X33d1_Number_of_Sessions__c = 5;
     	testTreatment.X33b12_Date_Commenced__c = testTreatment.X21a_Date_This_treatment_started__c;
     	testTreatment.X33d12_Number_of_Sessions__c = 5;
     	update testTreatment;
     	
     	HRB_Form__c checkTreatment = [select X33c20_Date_Completed__c, X33d20_Number_of_Sessions__c from HRB_Form__c where id = :testTreatment.id];
     	system.assertEquals (0, checkTreatment.X33d20_Number_of_Sessions__c);
     	system.assertEquals (null, checkTreatment.X33c20_Date_Completed__c);
     	
     	
    }
    
    static testMethod void TestEnsure_That_Q3321c_and_Q3321d_Are_Blank ()
    {
     	HRB_Form__c testTreatment = TestHRBFormRules2.TestQ25_to_Q28_Substances_are_all_different();
     	testTreatment.X37_Date_of_Final_Discharge__c = null;
     	testTreatment.X33b1_Date_Commenced__c = testTreatment.X21a_Date_This_treatment_started__c;
     	testTreatment.X33d1_Number_of_Sessions__c = 5;
     	testTreatment.X33b12_Date_Commenced__c = testTreatment.X21a_Date_This_treatment_started__c;
     	testTreatment.X33d12_Number_of_Sessions__c = 5;
     	update testTreatment;
     	
     	HRB_Form__c checkTreatment = [select X33c21_Date_Completed__c, X33d21_Number_of_Sessions__c from HRB_Form__c where id = :testTreatment.id];
     	system.assertEquals (0, checkTreatment.X33d21_Number_of_Sessions__c);
     	system.assertEquals (null, checkTreatment.X33c21_Date_Completed__c);
     	
     	
    }
    
    static testMethod void TestEnsure_That_Q3323c_and_Q3323d_Are_Blank ()
    {
     	HRB_Form__c testTreatment = TestHRBFormRules2.TestQ25_to_Q28_Substances_are_all_different();
     	testTreatment.X37_Date_of_Final_Discharge__c = null;
     	testTreatment.X33b1_Date_Commenced__c = testTreatment.X21a_Date_This_treatment_started__c;
     	testTreatment.X33d1_Number_of_Sessions__c = 5;
     	testTreatment.X33b12_Date_Commenced__c = testTreatment.X21a_Date_This_treatment_started__c;
     	testTreatment.X33d12_Number_of_Sessions__c = 5;
     	update testTreatment;
     	
     	HRB_Form__c checkTreatment = [select X33c23_Date_Completed__c, X33d23_Number_of_Sessions__c from HRB_Form__c where id = :testTreatment.id];
     	system.assertEquals (0, checkTreatment.X33d23_Number_of_Sessions__c);
     	system.assertEquals (null, checkTreatment.X33c23_Date_Completed__c);
     	
     	
    }
    static testMethod void TestEnsure_That_Q3328c_and_Q3328d_Are_Blank ()
    {
     	HRB_Form__c testTreatment = TestHRBFormRules2.TestQ25_to_Q28_Substances_are_all_different();
     	testTreatment.X37_Date_of_Final_Discharge__c = null;
     	testTreatment.X33b1_Date_Commenced__c = testTreatment.X21a_Date_This_treatment_started__c;
     	testTreatment.X33d1_Number_of_Sessions__c = 5;
     	testTreatment.X33b12_Date_Commenced__c = testTreatment.X21a_Date_This_treatment_started__c;
     	testTreatment.X33d12_Number_of_Sessions__c = 5;
     	update testTreatment;
     	
     	HRB_Form__c checkTreatment = [select X33c28_Date_Completed__c, X33d28_Number_of_Sessions__c from HRB_Form__c where id = :testTreatment.id];
     	system.assertEquals (0, checkTreatment.X33d28_Number_of_Sessions__c);
     	system.assertEquals (null, checkTreatment.X33c28_Date_Completed__c);
     	
     	
    }
}