src/objects/NDTRS_2016_Report__c.object
<CustomObject>
    <description>Used to select the range and type of NDTRS 2016 Report</description>
    <fields>
        <fullName>From_Assessment_Date__c</fullName>
        <label>From Assessment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>To_Assessment_Date__c</fullName>
        <label>To Assessment Date</label>
        <type>Date</type>
    </fields>
    <label>NDTRS LINK Report</label>
    <nameField>
        <displayFormat>NDTRS-{0000}</displayFormat>
        <label>NDTRS LINK Report Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NDTRS LINK Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/NDTRS_Drugs__c.object
<CustomObject>
    <fields>
        <fullName>Item_Code__c</fullName>
        <label>Item Code</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>NDTRS Drug</label>
    <nameField>
        <label>NDTRS Drugs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NDTRS Drugs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/NDTRS_Form_2016__c.object
<CustomObject>
    <description>Record of Treatment - Section D, E, F, G and H of NDTRS 2016 form</description>
    <fields>
        <fullName>NDTRS_2016_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NDTRS 2016 Report</label>
        <referenceTo>NDTRS_2016_Report__c</referenceTo>
        <relationshipName>NDTRS_2016_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>X13_2_Drug_specify__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>13.2 Drug (specify)</label>
        <referenceTo>NDTRS_Drugs__c</referenceTo>
        <relationshipName>NDTRS_2016_Forms6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>X21a_Main_drug__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>21a Main drug</label>
        <referenceTo>NDTRS_Drugs__c</referenceTo>
        <relationshipName>NDTRS_2016_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>X22a_Drug_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>22a Drug 2</label>
        <referenceTo>NDTRS_Drugs__c</referenceTo>
        <relationshipName>NDTRS_2016_Forms1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>X23a_Drug_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>23a Drug 3</label>
        <referenceTo>NDTRS_Drugs__c</referenceTo>
        <relationshipName>NDTRS_2016_Forms2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>X24a_Drug_4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>24a Drug 4</label>
        <referenceTo>NDTRS_Drugs__c</referenceTo>
        <relationshipName>NDTRS_2016_Forms3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>X25a_Drug_5__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>25a Drug 5</label>
        <referenceTo>NDTRS_Drugs__c</referenceTo>
        <relationshipName>NDTRS_2016_Forms4</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>NDTRS LINK Form</label>
    <nameField>
        <label>NDTRS LINK Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NDTRS LINK Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/NDTRS2016ReportController.cls
/*
	Author: Eamon Kelly, Enclude
	Author: Pedro Gonzalez, Enclude
	Purpose: Extract the fields for upload to HRB Link. 
	Security note: In practice only the administrator will have access to the NDTRS_2016_Treatment_Report page
	Called from: NDTRS_2016_Treatment_Report
	Tested in: TestNDTRSReports
*/
public with sharing class NDTRS2016ReportController 
{
    private NDTRS_Form_2016__c[] TreatmentsWithClientsList; // these are the NDTRS treatment forms
    private NDTRS_2016_Report__c reportParams; // this will be the object with the date range 
 	private static List<Schema.FieldSetMember> treatmentFieldsSectionsEtoG = new List<Schema.FieldSetMember>();
 	private static List<Schema.FieldSetMember> treatmentFieldsSectionH = new List<Schema.FieldSetMember>();
    
    public list<treatmentWrapper> treatmentWrappers {get;set;}
    public class treatmentWrapper
    {
    	public NDTRS_Form_2016__c treat {get;set;}
    	public treatmentWrapper (NDTRS_Form_2016__c oneTreatment)
    	{
    		treat = oneTreatment;
    	}
    	public string getFieldsSectionsEtoG ()
    	{
    		return getFields (NDTRS2016ReportController.treatmentFieldsSectionsEtoG);
    	}	
    	
    	public string getFieldsSectionH ()
    	{
    		return getFields (NDTRS2016ReportController.treatmentFieldsSectionH);
    	}	

    	private String getFields (list<Schema.FieldSetMember> fieldSet)
    	{
    		String fieldValues = '';
    		for (Schema.FieldSetMember oneField : fieldSet)
    		{
    			Schema.DisplayType fieldType = oneField.getType();
    			system.debug ('FieldType is: ' + fieldType);
    			system.debug ('Value is: ' + treat.get(oneField.getFieldPath()));
    			
				if (fieldType == DisplayType.Date)
                {
	    			if (treat.get(oneField.getFieldPath()) == null) fieldValues += ',';
	    			else fieldValues += ','+ ((Date)treat.get(oneField.getFieldPath())).format();
                }
                else if (fieldType == DisplayType.Double || fieldType == DisplayType.Integer) 
                {
                	if (treat.get(oneField.getFieldPath()) == null) fieldValues += ',0';
	    			else fieldValues += ','+ treat.get(oneField.getFieldPath());
                }
                else if (fieldType == DisplayType.Boolean)
                {
                    if((Boolean)(treat.get(oneField.getFieldPath()))== true) fieldValues += ',1';  
					else fieldValues += ',0';
                }    			
    			else
    			{
                	if (treat.get(oneField.getFieldPath()) == null) fieldValues += ',0';
    				else fieldValues += ','+ treat.get(oneField.getFieldPath());
    			}
    		}
    		return fieldValues;
    	}
    }
    
    public NDTRS2016ReportController (ApexPages.StandardController controller)
    {
        this.reportParams = (NDTRS_2016_Report__c)controller.getRecord();
        Initialise ();
        treatmentFieldsSectionsEtoG = ReadFieldList ('ReportFieldsSectionsEtoG');
        treatmentFieldsSectionH = ReadFieldList ('ReportFieldsSectionH');
    }
    
    private void Initialise ()
    {
        reportParams = [select id, From_Assessment_Date__c, To_Assessment_Date__c from NDTRS_2016_Report__c where id = :reportParams.id];
        
        String queryString = 'select ';
        queryString += NDTRSHelperFunctions.GetAllFieldsFromNDTRSForm ();
        queryString += NDTRSHelperFunctions.GetAllFieldsFromClient ();
        queryString += ', X21a_Main_drug__r.Item_Code__c, X22a_Drug_2__r.Item_Code__c, X23a_Drug_3__r.Item_Code__c, X24a_Drug_4__r.Item_Code__c, X25a_Drug_5__r.Item_Code__c';
        queryString += ', X13_2_Drug_specify__r.Item_Code__c';
        queryString += ' from NDTRS_Form_2016__c where NDTRS_2016_Report__c = \'' + reportParams.Id + '\'';
        System.Debug (queryString);
        TreatmentsWithClientsList = Database.query(queryString);
        
        treatmentWrappers = new list<treatmentWrapper>();
        for (NDTRS_Form_2016__c oneTreatment : TreatmentsWithClientsList)
        {
        	treatmentWrappers.add (new treatmentWrapper(oneTreatment));
        }
    }

    
    public NDTRS_Form_2016__c[] getTreatmentsWithClients()
    {
        return TreatmentsWithClientsList;
    }
    
    private list<Schema.FieldSetMember>	ReadFieldList (String fieldSetName)
    {
    	Schema.FieldSet fs1 = Schema.SObjectType.NDTRS_Form_2016__c.fieldSets.getMap().get(fieldSetName);
    	return fs1.getFields();
    }
}