src/objects/Referral__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Referrals</relationshipLabel>
        <relationshipName>Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_of_Referral__c</fullName>
        <label>Date of Referral</label>
        <type>Date</type>
    </fields>
    <label>Referral</label>
    <nameField>
        <label>Referral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/testCreateReferralTrigger.cls
@isTest
private class testCreateReferralTrigger {

    static testMethod void testAutoNamingOfReferral()
    {
        Contact youngPerson = new Contact (LastName = 'Kelly');
        insert youngPerson;
        Contact youngPerson2 = new Contact (LastName = 'Smith');
        insert youngPerson2;
 		Referral__c ref = new Referral__c (Client__c = youngPerson.id, Date_of_Referral__c=system.today(), Name='x');
 		insert ref;
 		ref = [select Name from Referral__c where ID=:ref.id];
 		system.assert (ref.Name.Contains ('Kelly'));
 	}
}